In [1]:
!git clone https://github.com/yacinemebarki/talk_like_me_gpt

Cloning into 'talk_like_me_gpt'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 49 (delta 14), reused 42 (delta 8), pack-reused 0 (from 0)
Receiving objects: 100% (49/49), 2.62 MiB | 7.25 MiB/s, done.
Resolving deltas: 100% (14/14), done.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/content/talk_like_me_gpt/data/message.csv")
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
88732,ÙØ´ÙÙØ§,Yacine Mebarki,1665091715875
88733,ØØØØ,Yacine Mebarki,1665091659314
88734,ÙØ§Ø³ÙÙ,Instagram User,1665091578941
88735,ÙØ´ Ø¹Ø¨Ø¯Ù,Yacine Mebarki,1665000590565
88736,Instagram User sent an attachment.,Instagram User,1665000509441

In [4]:
import re

def clean(mes):
  pattern = re.compile(r"(http[s]?://\S+)|[^\x00-\x7F]")
  return bool(pattern.search(mes))

In [5]:
df=df[df["content"].apply(clean)==False]
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
88718,Mat7rshsh,Yacine Mebarki,1663535817836
88719,Instagram User sent an attachment.,Instagram User,1666436431597
88720,Instagram User sent an attachment.,Instagram User,1666254455735
88721,Instagram User sent an attachment.,Instagram User,1666252975962
88736,Instagram User sent an attachment.,Instagram User,1665000509441

In [6]:
df=df[~(df["content"].str.contains('sent an attachment',case=False,na=False)|
      (df["content"]=="You missed an audio call")|
      (df["content"]=="You started an audio call")|
        (df["content"]=="Audio call started")|
        (df["content"]=="Audio call ended")|
        (df["content"].str.contains('started an audio call',case=False,na=False))|
        (df["content"]=="Liked a message"))]
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
6,Yacin,Instagram User,1750440008927
...,...,...,...
88714,Zino ousama tan,Wð©¸,1663535934578
88715,Rayne than darha story,Yacine Mebarki,1663535914924
88716,Makach mnha,Wð©¸,1663535862990
88717,Hhh,Wð©¸,1663535849006
88718,Mat7rshsh,Yacine Mebarki,1663535817836

In [7]:
df=df.reset_index()
df=df.drop(columns=["index"])
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,Yacin,Instagram User,1750440008927
...,...,...,...
53278,Zino ousama tan,Wð©¸,1663535934578
53279,Rayne than darha story,Yacine Mebarki,1663535914924
53280,Makach mnha,Wð©¸,1663535862990
53281,Hhh,Wð©¸,1663535849006
53282,Mat7rshsh,Yacine Mebarki,1663535817836

In [8]:
df['next_content'] = df['content'].shift(-1)
df['next_sender'] = df['sender'].shift(-1)

In [9]:
df.rename(columns={"content":"answer","next_content":"message"}, inplace=True)
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
1,Yacine Lyom 3aa 9,Instagram User,1752244626530,Lala,Yacine Mebarki
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
4,Yacin,Instagram User,1750440008927,3endi shghl dok,Yacine Mebarki
...,...,...,...,...,...
53278,Zino ousama tan,Wð©¸,1663535934578,Rayne than darha story,Yacine Mebarki
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53280,Makach mnha,Wð©¸,1663535862990,Hhh,Wð©¸
53281,Hhh,Wð©¸,1663535849006,Mat7rshsh,Yacine Mebarki
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [10]:
df=df[df["sender"]=="Yacine Mebarki"]
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
5,3endi shghl dok,Yacine Mebarki,1750087644305,Man9dersh,Yacine Mebarki
6,Man9dersh,Yacine Mebarki,1750087636879,Ntl3o oumb3d nontrino chwiya,Instagram User
...,...,...,...,...,...
53273,Wesh wadoud tji 3shya,Yacine Mebarki,1731156585337,Ok,Yacine Mebarki
53274,Ok,Yacine Mebarki,1685647730830,B3atilou,Wð©¸
53277,Zinou hbt m3aya lljam3,Yacine Mebarki,1663535955943,Zino ousama tan,Wð©¸
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [11]:
df=df[df["next_sender"]!="Yacine Mebarki"]
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
6,Man9dersh,Yacine Mebarki,1750087636879,Ntl3o oumb3d nontrino chwiya,Instagram User
8,Lala,Yacine Mebarki,1750078181154,Makch tontrini,Instagram User
10,Wlah walou mkash ga3,Yacine Mebarki,1750078074006,Yacin kach match,Instagram User
...,...,...,...,...,...
53271,Asm3 rani fi plassa champ na9ss,Yacine Mebarki,1731520839382,Ih,Wð©¸
53274,Ok,Yacine Mebarki,1685647730830,B3atilou,Wð©¸
53277,Zinou hbt m3aya lljam3,Yacine Mebarki,1663535955943,Zino ousama tan,Wð©¸
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [12]:
df=df.dropna(subset=['message', 'answer'])

In [13]:
import tensorflow as tf
from tensorflow.keras import models,layers
from tensorflow.keras.layers import MultiHeadAttention,LayerNormalization
class decoder:

    def __init__(self,num_heads,key_dim):
        model=models.Sequential()
        model.add(layers.Dense(256,activation="relu"))
        model.add(layers.Dense(64))
        self.fnn=model
        self.msa=MultiHeadAttention(num_heads,key_dim)
        self.cross_att = MultiHeadAttention(num_heads, key_dim)
        self.ln1 = LayerNormalization()
        self.ln2 = LayerNormalization()


    def forward(self,x,enc_out):
        out1=self.msa(query=x,value=x,key=x,use_causal_mask=True)

        x1=self.ln1(x+out1)
        cross = self.cross_att(query=x1, key=enc_out, value=enc_out)

        out2=self.fnn(cross)
        x2=self.ln2(cross+out2)
        return x2

In [14]:
class encoder:

  def __init__(self,num_heads,key_dim):
    model=models.Sequential()
    model.add(layers.Dense(256,activation="relu"))
    model.add(layers.Dense(64))
    self.fnn=model
    self.msa=MultiHeadAttention(num_heads,key_dim)
    self.ln1 = LayerNormalization()
    self.ln2 = LayerNormalization()

  def forward(self,x):
    out1=self.msa(query=x,value=x,key=x)
    x1=self.ln1(x+out1)
    out2=self.fnn(x1)
    x2=self.ln2(x1+out2)
    return x2

In [15]:
from tensorflow.keras.layers import Dense,Embedding
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.optimizers import Adam




class model:

    def __init__(self,n_decoder,n_encoder,input_size,num_heads,key_dim,n_token):
        self.input_size=input_size
        self.enlayers=[]
        self.delayers=[]
        self.dense=Dense(n_token,activation="softmax")
        self.emb=Embedding(input_dim=n_token,output_dim=64,input_length=32)
        self.optimizer = tf.keras.optimizers.Adam(0.01)
        self.loss_fn = SparseCategoricalCrossentropy()
        for i in range(n_encoder):
          self.enlayers.append(encoder(num_heads,key_dim))
        for i in range(n_decoder):
          self.delayers.append(decoder(num_heads,key_dim))




    def fit(self,x,y,epoch):
        n_sample=len(x)
        for ep in range(epoch):
            for i in range(n_sample):
                a = tf.expand_dims(x[i], axis=0)
                with tf.GradientTape() as tape:
                    a=self.emb(a)
                    for l in self.enlayers:
                        a=l.forward(a)
                        enc_out=a
                    for l in self.delayers:
                        a=l.forward(a,enc_out)

                    out=self.dense(a)
                    y_true = tf.expand_dims(y[i], axis=0)
                    loss=self.loss_fn(y_true, out)

                variables=self.dense.trainable_variables
                for l in reversed(self.delayers):
                    variables += l.fnn.trainable_variables
                    variables += l.msa.trainable_variables
                    variables += l.msa.trainable_variables


                for l in reversed(self.enlayers):
                    variables += l.fnn.trainable_variables
                    variables += l.msa.trainable_variables
                variables +=self.emb.trainable_variables




                grads = tape.gradient(loss, variables)
                self.optimizer.apply_gradients(zip(grads,variables))

In [16]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tok_m=Tokenizer(oov_token="<oov>")
tok_m.fit_on_texts(df["message"])
tok_a=Tokenizer(oov_token="<oov>")
tok_a.fit_on_texts(df["answer"])

In [17]:
x_seq=tok_m.texts_to_sequences(df["message"])
y_seq=tok_a.texts_to_sequences(df["answer"])
x_seq=pad_sequences(x_seq,maxlen=32)
y_seq=pad_sequences(y_seq,maxlen=32)

In [18]:
pip=model(1,2,32,12,4,len(tok_m.word_index)+1)
pip.fit(x_seq,y_seq,5)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

KeyboardInterrupt: