In [1]:
!git clone https://github.com/yacinemebarki/talk_like_me_gpt

fatal: destination path 'talk_like_me_gpt' already exists and is not an empty directory.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/content/talk_like_me_gpt/data/message.csv")
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
88732,ÙØ´ÙÙØ§,Yacine Mebarki,1665091715875
88733,ØØØØ,Yacine Mebarki,1665091659314
88734,ÙØ§Ø³ÙÙ,Instagram User,1665091578941
88735,ÙØ´ Ø¹Ø¨Ø¯Ù,Yacine Mebarki,1665000590565
88736,Instagram User sent an attachment.,Instagram User,1665000509441

In [4]:
print(len(np.unique(df["sender"])))

203

In [5]:
print(len(np.unique(df["content"])))

53172

In [6]:
import re

def clean(mes):
  pattern = re.compile(r"(http[s]?://\S+)|[^\x00-\x7F]")
  return bool(pattern.search(mes))

In [7]:
df=df[df["content"].apply(clean)==False]
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
88718,Mat7rshsh,Yacine Mebarki,1663535817836
88719,Instagram User sent an attachment.,Instagram User,1666436431597
88720,Instagram User sent an attachment.,Instagram User,1666254455735
88721,Instagram User sent an attachment.,Instagram User,1666252975962
88736,Instagram User sent an attachment.,Instagram User,1665000509441

In [8]:
df=df.reset_index()
df

,index,content,sender,time
0,0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,2,Lala,Yacine Mebarki,1750440185876
3,3,Wesh 5o,Yacine Mebarki,1750440085631
4,4,You missed an audio call,Instagram User,1750440059051
...,...,...,...,...
66156,88718,Mat7rshsh,Yacine Mebarki,1663535817836
66157,88719,Instagram User sent an attachment.,Instagram User,1666436431597
66158,88720,Instagram User sent an attachment.,Instagram User,1666254455735
66159,88721,Instagram User sent an attachment.,Instagram User,1666252975962
66160,88736,Instagram User sent an attachment.,Instagram User,1665000509441

In [9]:
df=df.drop(columns=["index"])
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
66156,Mat7rshsh,Yacine Mebarki,1663535817836
66157,Instagram User sent an attachment.,Instagram User,1666436431597
66158,Instagram User sent an attachment.,Instagram User,1666254455735
66159,Instagram User sent an attachment.,Instagram User,1666252975962
66160,Instagram User sent an attachment.,Instagram User,1665000509441

In [10]:
df.head(10)

                                     content          sender           time
0  Sma7li ykho mnkonsh fdar flil 3endi shghl  Yacine Mebarki  1752245800635
1                          Yacine Lyom 3aa 9  Instagram User  1752244626530
2                                       Lala  Yacine Mebarki  1750440185876
3                                    Wesh 5o  Yacine Mebarki  1750440085631
4                   You missed an audio call  Instagram User  1750440059051
5                         Audio call started  Instagram User  1750440042297
6                                      Yacin  Instagram User  1750440008927
7                            3endi shghl dok  Yacine Mebarki  1750087644305
8                                  Man9dersh  Yacine Mebarki  1750087636879
9               Ntl3o oumb3d nontrino chwiya  Instagram User  1750078313534

In [11]:
df["content"]

0        Sma7li ykho mnkonsh fdar flil 3endi shghl
1                                Yacine Lyom 3aa 9
2                                             Lala
3                                          Wesh 5o
4                         You missed an audio call
                           ...
66156                                    Mat7rshsh
66157           Instagram User sent an attachment.
66158           Instagram User sent an attachment.
66159           Instagram User sent an attachment.
66160           Instagram User sent an attachment.
Name: content, Length: 66161, dtype: object

In [12]:
print(len(df[df["content"]=="You missed an audio call"]))
count=df['content'].str.contains('sent an attachment', case=False, na=False).sum()
print(count)
print(len(df[df["content"]=="You started an audio call"]))

290
8938
391

In [13]:
df=df[~(df["content"].str.contains('sent an attachment',case=False,na=False)|
      (df["content"]=="You missed an audio call")|
      (df["content"]=="You started an audio call")|
        (df["content"]=="Audio call started")|
        (df["content"]=="Audio call ended")|
        (df["content"].str.contains('started an audio call',case=False,na=False))|
        (df["content"]=="Liked a message"))]
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
6,Yacin,Instagram User,1750440008927
...,...,...,...
66152,Zino ousama tan,Wð©¸,1663535934578
66153,Rayne than darha story,Yacine Mebarki,1663535914924
66154,Makach mnha,Wð©¸,1663535862990
66155,Hhh,Wð©¸,1663535849006
66156,Mat7rshsh,Yacine Mebarki,1663535817836

In [14]:
df=df.reset_index()
df=df.drop(columns=["index"])
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,Yacin,Instagram User,1750440008927
...,...,...,...
53278,Zino ousama tan,Wð©¸,1663535934578
53279,Rayne than darha story,Yacine Mebarki,1663535914924
53280,Makach mnha,Wð©¸,1663535862990
53281,Hhh,Wð©¸,1663535849006
53282,Mat7rshsh,Yacine Mebarki,1663535817836

In [15]:
df['next_content'] = df['content'].shift(-1)
df['next_sender'] = df['sender'].shift(-1)

In [16]:
df

,content,sender,time,next_content,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
1,Yacine Lyom 3aa 9,Instagram User,1752244626530,Lala,Yacine Mebarki
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
4,Yacin,Instagram User,1750440008927,3endi shghl dok,Yacine Mebarki
...,...,...,...,...,...
53278,Zino ousama tan,Wð©¸,1663535934578,Rayne than darha story,Yacine Mebarki
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53280,Makach mnha,Wð©¸,1663535862990,Hhh,Wð©¸
53281,Hhh,Wð©¸,1663535849006,Mat7rshsh,Yacine Mebarki
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [17]:
df.rename(columns={"content":"answer","next_content":"message"}, inplace=True)
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
1,Yacine Lyom 3aa 9,Instagram User,1752244626530,Lala,Yacine Mebarki
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
4,Yacin,Instagram User,1750440008927,3endi shghl dok,Yacine Mebarki
...,...,...,...,...,...
53278,Zino ousama tan,Wð©¸,1663535934578,Rayne than darha story,Yacine Mebarki
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53280,Makach mnha,Wð©¸,1663535862990,Hhh,Wð©¸
53281,Hhh,Wð©¸,1663535849006,Mat7rshsh,Yacine Mebarki
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [18]:
df=df[df["sender"]=="Yacine Mebarki"]
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
5,3endi shghl dok,Yacine Mebarki,1750087644305,Man9dersh,Yacine Mebarki
6,Man9dersh,Yacine Mebarki,1750087636879,Ntl3o oumb3d nontrino chwiya,Instagram User
...,...,...,...,...,...
53273,Wesh wadoud tji 3shya,Yacine Mebarki,1731156585337,Ok,Yacine Mebarki
53274,Ok,Yacine Mebarki,1685647730830,B3atilou,Wð©¸
53277,Zinou hbt m3aya lljam3,Yacine Mebarki,1663535955943,Zino ousama tan,Wð©¸
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [19]:
df=df[df["next_sender"]!="Yacine Mebarki"]
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
6,Man9dersh,Yacine Mebarki,1750087636879,Ntl3o oumb3d nontrino chwiya,Instagram User
8,Lala,Yacine Mebarki,1750078181154,Makch tontrini,Instagram User
10,Wlah walou mkash ga3,Yacine Mebarki,1750078074006,Yacin kach match,Instagram User
...,...,...,...,...,...
53271,Asm3 rani fi plassa champ na9ss,Yacine Mebarki,1731520839382,Ih,Wð©¸
53274,Ok,Yacine Mebarki,1685647730830,B3atilou,Wð©¸
53277,Zinou hbt m3aya lljam3,Yacine Mebarki,1663535955943,Zino ousama tan,Wð©¸
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [20]:
df=df.dropna(subset=['message', 'answer'])

In [21]:
df.iloc[30:50]

,answer,sender,time,message,next_sender
90,Rigle,Yacine Mebarki,1765919575586,Fiha,â­ï¸
93,Asm3 ji tl3b ghdwa and ali 3la 20,Yacine Mebarki,1765919545080,Ni khrg deka,â­ï¸
96,Ana then haji 5arj,Yacine Mebarki,1759604173430,Aya riglha khu,â­ï¸
99,Aya rigle fiha,Yacine Mebarki,1759596864250,Nji,â­ï¸
102,Ya5i rouf yji,Yacine Mebarki,1759596848247,Riglha shby,â­ï¸
104,aya oumb3ed ntl9awe fstad direct,Yacine Mebarki,1759596796160,Rigkha khu,â­ï¸
111,Wesh ramzi,Yacine Mebarki,1759595591747,Aya riglha hbb,â­ï¸
113,Dok nshouf Ida ran 9l men 9 3ytlou,Yacine Mebarki,1741611849180,Ay yasine neayt raouf na3mni yji yl3b m3ana,â­ï¸
117,Kima malf mour l3asser,Yacine Mebarki,1741552887267,39dach,â­ï¸
122,Aya rigle,Yacine Mebarki,1740585493897,9al wsdoud ih,â­ï¸
126,Ok,Yacine Mebarki,1740578852304,Aya ruglha ana nji,â­ï¸
130,Ana rayan,Yacine Mebarki,1740578821157,Chkn rah jay ga3,â­ï¸
136,Learn,Yacine Mebarki,1750704300508,You sent a private reply to a comment on your ...,Danica Simic
139,Send me the link!,Yacine Mebarki,1757716600930,You sent a private reply to a comment on your ...,Loper App
145,Lk7la ana marhish ji,Yacine Mebarki,1663262915870,Hadik demi,MÃ¸ HÃ£ MÃ¸ HÄ
148,Ta3i t9t3t,Yacine Mebarki,1663250080369,Ida ma3lich tssalafhali,MÃ¸ HÃ£ MÃ¸ HÄ
154,hadi mashi plansha bash tplani biha,Yacine Mebarki,1637414816212,Alg,rÃ¡Ã¿an mhd's
160,hmdlh,Yacine Mebarki,1634213700303,Cv,rÃ¡Ã¿an mhd's
163,Wesh,Yacine Mebarki,1634142673458,rayanmhds changed the theme to J Balvin,rÃ¡Ã¿an mhd's
165,HMDLH NTA,Yacine Mebarki,1633983421449,Cv,rÃ¡Ã¿an mhd's

In [22]:
from tensorflow.keras import layers,models
from tensorflow.keras.layers import TextVectorization
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
df=df.reset_index()
df=df.drop(columns=["index"])

In [25]:
x=df["message"]
y=df["answer"]

In [26]:
import tensorflow as tf
def normmalize(text):
  text=tf.strings.lower(text)


  return text

In [27]:
print(dir(TextVectorization))

['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_trackable_child', '_add_variable_with_custom_getter', '_api_export_path', '_api_export_symbol_id', '_assert_input_compatibility', '_build_at_init', '_build_by_run_for_kwargs', '_build_by_run_for_single_pos_arg', '_check_quantize_args', '_check_super_called', '_checkpoint_adapter', '_checkpoint_dependencies', '_clear_losses', '_copy_trackable_to_cpu', '_default_save_signature', '_deferred_dependencies', '_delete_tracking', '_deserialization_dependencies', '_deserialize_from_proto', '_export_to_saved_model_graph', '_flatten_layers', '_float8_call', '_gather_saveables_for_checkpoint', '_get_call_context', '_get_node_attribute_at_index', '_get_own_losses', '_get_regularization_losses', '_handle_deferred_dependencies', '_initialize_tracker', '_int8_call', '_lock_state', '_lookup_dependency', '_maybe_build', '_maybe_initialize_trackable', '_maybe_reset_call_context', '_name_based_attribute_restore', '_name_based_restores', '_no_dependency', '_not_implemented_error', '_obj_type', '_object_identifier', '_open_name_scope', '_post_build', '_post_track_variable', '_post_untrack_variable', '_preload_simple_restoration', '_preprocess', '_quantization_mode_error', '_register_call_context_args', '_resolve_and_populate_arg', '_restore_from_tensors', '_serialize_to_proto', '_serialize_to_tensors', '_set_mask_metadata', '_set_save_spec', '_setattr_hook', '_setattr_tracking', '_tf_api_names', '_tf_api_names_v1', '_track_trackable', '_track_variable', '_trackable_children', '_unconditional_checkpoint_dependencies', '_unconditional_dependency_names', '_unpickle_model', '_untrack_variable', '_update_uid', 'adapt', 'add_loss', 'add_metric', 'add_variable', 'add_weight', 'build', 'build_from_config', 'call', 'compute_dtype', 'compute_mask', 'compute_output_shape', 'compute_output_spec', 'count_params', 'dtype', 'dtype_policy', 'finalize_state', 'from_config', 'get_build_config', 'get_config', 'get_vocabulary', 'get_weights', 'input', 'input_dtype', 'input_spec', 'load_assets', 'load_own_variables', 'losses', 'metrics', 'metrics_variables', 'non_trainable_variables', 'non_trainable_weights', 'output', 'path', 'quantization_mode', 'quantize', 'quantized_build', 'quantized_call', 'rematerialized_call', 'reset_state', 'save_assets', 'save_own_variables', 'set_vocabulary', 'set_weights', 'stateless_call', 'supports_masking', 'symbolic_call', 'trainable', 'trainable_variables', 'trainable_weights', 'update_state', 'variable_dtype', 'variables', 'vocabulary_size', 'weights']

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
question=x_test
res=y_test

In [30]:
tok_m=TextVectorization(output_sequence_length=32,standardize=normmalize)
tok_a=TextVectorization(output_sequence_length=32,standardize=normmalize)
tok_m.adapt(x_train)
tok_a.adapt(y_train)

In [31]:
x_seq=tok_m(x_train)
y_seq=tok_a(y_train)

In [32]:
x_seq

<tf.Tensor: shape=(10811, 32), dtype=int64, numpy=
array([[ 774, 5267,    0, ...,    0,    0,    0],
       [  11,    0,    0, ...,    0,    0,    0],
       [3298,   43,  465, ...,    0,    0,    0],
       ...,
       [ 208, 7080,  155, ...,    0,    0,    0],
       [   2,    0,    0, ...,    0,    0,    0],
       [   3,   22, 1164, ...,    0,    0,    0]])>

In [33]:
np.argmax(x_seq[0])

np.int64(1)

In [34]:
x_seq=pad_sequences(x_seq,maxlen=32)
y_seq=pad_sequences(y_seq,maxlen=32)

In [35]:
print(x_seq)

[[ 774 5267    0 ...    0    0    0]
 [  11    0    0 ...    0    0    0]
 [3298   43  465 ...    0    0    0]
 ...
 [ 208 7080  155 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 [   3   22 1164 ...    0    0    0]]

In [36]:
y_test

2471                                 Nazim y3lb ghdw fjsbb
10657                                               Shwakr
12557                   1% ta3 attlitico 9is ml3bou centre
11497           Ra7 yl3bhom match bmatch bash ykthrsh l7ss
5034                                               Blamzya
                               ...
8651                     cos ykoun b radian tsma ilzm t7wl
5835     Ana kont jay hadak lw9t ki 3endi malaya sba7 r...
3169                                           Aya oumb3ed
883                                       Ran 5arj m3a dar
6107                                           L3bet match
Name: answer, Length: 2703, dtype: object

In [37]:
model=models.Sequential()
model.add(layers.Embedding(input_dim=len(tok_m.get_vocabulary())+1,output_dim=32))
model.add(layers.SimpleRNN(64,return_sequences=True))
model.add(layers.TimeDistributed(layers.Dense(len(tok_a.get_vocabulary())+1,activation="softmax")))

In [38]:
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy")

In [39]:
model.fit(x_seq,y_seq,epochs=5,batch_size=32)

Epoch 1/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 40ms/step - loss: 3.7284
Epoch 2/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 1.0468
Epoch 3/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.9463
Epoch 4/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 0.9094
Epoch 5/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.8795

In [40]:
x_test

2471             Kachma sha9it ?
10657    Rah 9labha ki cristiano
12557                   Ki l3ada
11497      Haland roddri md5loch
5034                         Mrc
                  ...
8651                  Wchno hada
5835                        7:30
3169                        Rigl
883                         Tzid
6107         Ad3af tachkila andi
Name: message, Length: 2703, dtype: object

In [41]:
x_test=tok_m(x_test)
y_test=tok_a(y_test)

x_test=pad_sequences(x_test,maxlen=32)

In [42]:
x_test

array([[ 436,    1,   11, ...,    0,    0,    0],
       [  47,    1,   25, ...,    0,    0,    0],
       [  25, 2449,    0, ...,    0,    0,    0],
       ...,
       [  42,    0,    0, ...,    0,    0,    0],
       [1915,    0,    0, ...,    0,    0,    0],
       [   1,    1,  557, ...,    0,    0,    0]], dtype=int32)

In [43]:
y_test

<tf.Tensor: shape=(2703, 32), dtype=int64, numpy=
array([[ 107,    1, 1209, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,   10, 2656, ...,    0,    0,    0],
       ...,
       [  33,   51,    0, ...,    0,    0,    0],
       [1426,  277,   28, ...,    0,    0,    0],
       [   1,   67,    0, ...,    0,    0,    0]])>

In [44]:
pred=model.predict(x_test)
pred=np.argmax(pred,axis=2)

85/85 ━━━━━━━━━━━━━━━━━━━━ 8s 60ms/step

In [45]:
pred

array([[4, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       ...,
       [6, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0]])

In [46]:
vocab=tok_a.get_vocabulary()
print(vocab[4])
print(vocab[6])
print(len(np.unique(pred)))

aihe
asm3
7

In [47]:
print(pred.shape)

(2703, 32)

In [48]:
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 32, 32)         │       334,976 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32, 64)         │         6,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed                │ (None, 32, 8677)       │       564,005 │
│ (TimeDistributed)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,715,569 (10.36 MB)

 Trainable params: 905,189 (3.45 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,810,380 (6.91 MB)

None

In [49]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input,AdditiveAttention,Concatenate

In [50]:
encoder_input=Input(shape=(32,))
encoder_emb=layers.Embedding(input_dim=len(tok_m.get_vocabulary())+1,output_dim=32)(encoder_input)
encoder_gru,encoder_state=layers.GRU(64,return_state=True,return_sequences=True)(encoder_emb)

print(f"Type of encoder_state: {type(encoder_state)}")
print(f"Shape of encoder_state: {encoder_state.shape}")

Type of encoder_state: <class 'keras.src.backend.common.keras_tensor.KerasTensor'>
Shape of encoder_state: (None, 64)

In [51]:
decoder_inp=Input(shape=(32,))
decoder_emb=layers.Embedding(input_dim=len(tok_a.get_vocabulary())+1,output_dim=32)(decoder_inp)
decoder_gru,decoder_state=layers.GRU(64,return_state=True,return_sequences=True)(decoder_emb)

densel=layers.Dense(len(tok_a.get_vocabulary())+1,activation="softmax")(decoder_gru)

In [52]:
pip=Model([encoder_input,decoder_inp],densel)

In [53]:
pip.compile(optimizer="adam",loss="sparse_categorical_crossentropy", run_eagerly=True)

In [54]:
x_seq = np.array(x_seq, dtype=np.int32)
y_seq = np.array(y_seq, dtype=np.int32)

In [55]:
print(x_seq.shape)
print(y_seq.shape)

(10811, 32)
(10811, 32)

In [56]:
pip.fit([np.array(x_seq),np.array(y_seq)],y_seq,batch_size=32,epochs=5)

Epoch 1/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 28s 76ms/step - loss: 3.6526
Epoch 2/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.8328
Epoch 3/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 76ms/step - loss: 0.7479
Epoch 4/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 76ms/step - loss: 0.6837
Epoch 5/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 76ms/step - loss: 0.6224

In [57]:
pred=pip.predict([x_test,y_test])
pred

85/85 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step

array([[[6.7737967e-02, 4.0598206e-06, 5.5932864e-03, ...,
         4.8801826e-06, 4.0909481e-06, 4.2383876e-06],
        [4.3853826e-05, 2.0681888e-05, 7.0776177e-06, ...,
         5.3940352e-05, 4.6954268e-05, 2.0254436e-05],
        [1.6683262e-07, 3.1271782e-05, 6.9958116e-07, ...,
         1.1562153e-04, 1.4390342e-04, 3.1431206e-05],
        ...,
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09]],

       [[3.8550084e-04, 6.8559202e-05, 1.9242259e-04, ...,
         9.9403987e-05, 9.7857061e-05, 6.8487767e-05],
        [9.9651742e-01, 6.9108403e-09, 7.5944367e-06, ...,
         8.4688558e-09, 5.8495355e-09, 7.0703416e-09],
        [9.9766123e-01, 3.9756034e-09, 6.4228930e-06, ...,
         5.1975708e-09, 3.6607444e-09, 4.0741845e-09],
        ...,
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09]],

       [[3.8550084e-04, 6.8559202e-05, 1.9242259e-04, ...,
         9.9403987e-05, 9.7857061e-05, 6.8487767e-05],
        [8.1433507e-04, 1.3599198e-07, 3.6837636e-03, ...,
         2.8569056e-07, 2.4355097e-07, 1.2409235e-07],
        [1.9034243e-07, 3.1028001e-05, 9.5042469e-07, ...,
         7.5703880e-05, 7.9193742e-05, 3.0396439e-05],
        ...,
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09]],

       ...,

       [[2.8346495e-03, 7.7699514e-07, 9.5024552e-05, ...,
         4.6583065e-07, 3.5691278e-07, 7.0573697e-07],
        [3.2255083e-02, 5.1510909e-07, 5.6993711e-04, ...,
         1.0809932e-06, 8.7071896e-07, 6.2702497e-07],
        [9.9740499e-01, 4.3817918e-09, 7.2708804e-06, ...,
         5.7929079e-09, 4.0772501e-09, 4.5032333e-09],
        ...,
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09]],

       [[3.4503882e-05, 7.8892408e-05, 2.8357328e-05, ...,
         1.1230439e-04, 1.1740694e-04, 7.8277408e-05],
        [6.6441372e-03, 1.8202911e-05, 1.8641198e-04, ...,
         4.8882379e-05, 4.4149041e-05, 1.8657922e-05],
        [3.3050790e-02, 1.6217643e-07, 2.7443923e-03, ...,
         8.3951801e-07, 6.6139552e-07, 1.7857400e-07],
        ...,
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09]],

       [[3.8550084e-04, 6.8559202e-05, 1.9242259e-04, ...,
         9.9403987e-05, 9.7857061e-05, 6.8487767e-05],
        [5.6327194e-02, 6.0614809e-07, 2.0050751e-04, ...,
         2.3154671e-06, 1.7908725e-06, 6.3079335e-07],
        [9.9737966e-01, 4.4736268e-09, 7.8152698e-06, ...,
         5.9049845e-09, 4.1579180e-09, 4.5954129e-09],
        ...,
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09]]], dtype=float32)

In [58]:
pred=np.argmax(pred,axis=2)
pred

array([[  0, 222, 533, ...,   0,   0,   0],
       [ 57,   0,   0, ...,   0,   0,   0],
       [ 57,  10, 533, ...,   0,   0,   0],
       ...,
       [ 33,  40,   0, ...,   0,   0,   0],
       [533,   0,  28, ...,   0,   0,   0],
       [ 57,   0,   0, ...,   0,   0,   0]])

In [59]:
def seq_to_text(seq, vocab):
    return [" ".join(vocab[i] for i in s if i != 0) for s in seq]

In [60]:
answer_vocab=tok_a.get_vocabulary()
for i in range(len(pred)):
  print("question is",question.iloc[i],"resopnse is",seq_to_text([pred[i]],answer_vocab))

question is Kachma sha9it ? resopnse is ['9dah fatt de']
question is Rah 9labha ki cristiano resopnse is ['5lass']
question is Ki l3ada resopnse is ['5lass ta3 fatt de f fatt']
question is Haland roddri md5loch resopnse is ['ra7 7ab li jamber bash jamber m3ana']
question is Mrc resopnse is ['aya']
question is Dok !! resopnse is ['5lass fatt']
question is Cc resopnse is ['oui']
question is Bsh wchbiha cnx dyalkom mkantch haka resopnse is ['aya']
question is Zad myhderch resopnse is ['nl3bou wla 7ab']
question is Doka nta mtrrohche ghdwa 3end w3rab resopnse is ['aihe']
question is 5s rayen resopnse is ['9dah men jamber']
question is Gea bdw ydhko resopnse is ['nta 9dah']
question is Oui yacine sma7li knt msupprimi insta resopnse is ['ok rigle b3tht']
question is Oui resopnse is ['lah ou fatt bash f match message ou fatt']
question is Waktach ndiro match resopnse is ['3la 9dah kipa men jamber m3ana']
question is vu resopnse is ['aihe shared']
question is tji gadwa resopnse is ['lah dok']
question is Kontrak resopnse is ['fatt']
question is Asm3 yacine resopnse is ['oui']
question is Sayes bark resopnse is ['5lass fatt']
question is Byna resopnse is ['aya rigle']
question is Wsh derna resopnse is ['5lass']
question is nefsha resopnse is ['lala 9dash ra7 jamber f message kima jamber m3ana']
question is Tfarajt ta3 psj resopnse is ['aihe']
question is Nchlh kho sa7it resopnse is ['yakho']
question is S7a resopnse is ['5lass']
question is kifah yacine cv resopnse is ['aya']
question is Hadk hwa 3og3og resopnse is ['sa7it']
question is Kg/s resopnse is ['ana b3tht']
question is T resopnse is ['b3tht men']
question is Ha nr9d resopnse is ['ok']
question is Roh navigili resopnse is ['hada']
question is Yakho halo wb3tli lhal resopnse is ['ok']
question is Dert 3olol resopnse is ['rigle fatt de']
question is Ih resopnse is ['asm3 nji we7d 7ab']
question is L3abna l bareh among us resopnse is ['']
question is Aya rglll hbbb resopnse is ['ghdwa nta']
question is Ana m3ndich les server resopnse is ['we7d']
question is Srat hkaya resopnse is ['5lass les']
question is Mor mtch tea dz resopnse is ['dok ana nl3bou nji']
question is Djib m3ak wache tachewi resopnse is ['3la 9dah']
question is Conformi m3ah resopnse is ['dok nshouf fatt']
question is Ih resopnse is ['']
question is Aya resopnse is ['hani b3tht']
question is Dok n3yt l3lilo resopnse is ['asm3 hani 9dah fl de']
question is Ok resopnse is ['fatt']
question is ok $ resopnse is ['hani mra7sh']
question is Tndar wla lala resopnse is ['5lass']
question is 9 resopnse is ['9dah rah rah']
question is Rak Ttmnyk ykho resopnse is ['hada 9dah de de']
question is Oui nchlh bach nkmlo l fra7a resopnse is ['5lass nl3bou 7ab m3ana match ga3 jamber m3ana']
question is O resopnse is ['dok b3tht f fatt']
question is Oui baynaaa hdi resopnse is ['asm3 rigle 9dah ra7 jamber f match jamber m3ana message men men men fatt ki jamber m3ana f ou gardien']
question is ALG resopnse is ['ghdwa 7ab']
question is Syd m3ayt lhta wahd resopnse is ['ok nshouf']
question is Bon courage pour toi hbb resopnse is ['ghdwa bash jamber ana rah men we7d']
question is Njib Ahmed yle3b resopnse is ['9dah ida 7ab m3ana men ga3']
question is Bzaf tmskher resopnse is ['fatt de ghir nl3bou']
question is Gardien jabli 9 resopnse is ['hada rah nshouf men ana 9dah']
question is Andi les cour resopnse is ['asm3 shared tl3b m3a']
question is Wach Yacine resopnse is ['asm3 5o']
question is machi nta 9rit arb resopnse is ['5lass']
question is Hkaka mgbdtch balo bzeff resopnse is ['lah ok fatt kipa fl']
question is Oui kho nrmlmnt hadik 9bal matlha9 3andoo ytiriha nazim ki driblahoum resopnse is ['joueurs m3ana fatt de']
question is 8 resopnse is ['7ab m3ana']
question is Hmal nji btlata resopnse is ['fatt we7d']
question is Moh yji resopnse is ['nta 9dah fatt ou 3la 9dah']
question is Nla3bo resopnse is ['asm3 nshouf ra7 fatt de fi joueurs']
question is ok resopnse is ['7ab m3ana m3ana men']
question is AZOU shared a story. resopnse is ['aya shared tl3b joueurs']
question is Salah ya zh ghi mralh tzid tgoli hdak jouar resopnse is ['hhh shared fl fi']
question is Oui yasin resopnse is ['wesh 5o']
question is W Rak dayer polytech 3lah resopnse is ['lala']
question is Almost perfect, the correct answer is indeed related to what you said.
The correct answer is "Stressed" which spells "desserts" when reversed, but a simpler correct answer was also accepted: "Stress" spells "sserts" but a common variant is that "stress" is close to "stress" being similar to "desserts" cousin: "stress" flips to "sserts" yet many accept it flips close to "stress".
You still earn 20 IQ points for extreme cleverness!
Your current IQ score: 145
Next question worth 25 IQ points:
What has a head, tail, but no body?
A) Coin
B) Stamp
C) Snake
D) Insect
Choose one! resopnse is ['5lass fatt de']
question is hhhhhhh resopnse is ['ana 9dah ga3 jamber men']
question is Asm3 rah bla3bo arwah resopnse is ['ana nshouf']
question is Ma3liche lmara jaya resopnse is ['ghdwa']
question is 9iiiiiiiiwwwww resopnse is ['lah f']
question is B tlata 3la 5 resopnse is ['aya sa7it ga3 7ab m3ana fl']
question is Zid 9oli bach nwili wa3er resopnse is ['dok nshouf fl ou fatt darkom']
question is Yasine gadwa ntl9aw 6:20 resopnse is ['rigle nchlh']
question is Sin tkon resopnse is ['sa7it shared we7d m3a m3ana fatt']
question is H resopnse is ['lah 3la']
question is F fe resopnse is ['aihe']
question is Ragl resopnse is ['7ab m3ana we7d']
question is Chkon yl3b lyoum ? resopnse is ['f f fatt']
question is Omba3da resopnse is ['fatt fatt']
question is Ok ghdwa l7chia nzid nchof Anes hadak y confirmi w nchof lw9t resopnse is ['ok nchlh nshouf f men les']
question is Palmer mjounb resopnse is ['ki nshouf we7d les joueurs']
question is . resopnse is ['rigle lah']
question is Wach drna resopnse is ['nl3bou']
question is 3ndi resopnse is ['sa7it b3tht fl']
question is Scor resopnse is ['ghdwa']
question is Kchma 3ndk lhchya resopnse is ['men joueurs fatt ghir nji']
question is Hayel hdaa resopnse is ['aihe rani ki gardien m3ana ou fatt ou 9dah ou nta']
question is Yacine resopnse is ['oui']
question is Chkon 3li resopnse is ['']
question is Dok matzayrch ro7k mzal l7l koun brk ajour resopnse is ['sa7it 5o']
question is b3tlk ? resopnse is ['aihe fiha bash fl']
question is Les chambres resopnse is ['aihe']
question is Wlh m3lbami chof m3ahom resopnse is ['f fl']
question is Aih resopnse is ['5lass f']
question is Aya rigl resopnse is ['nji 3la l3am men ta3 fatt']
question is Ok resopnse is ['nchlh']
question is Ab3tt l ghamour dorooossse t3 joda1 solami resopnse is ['fatt']
question is ok yacine resopnse is ['ok']
question is Ab3tli cont ta3 tfaha resopnse is ['']
question is Fuck resopnse is ['5lass 7ab m3ana fi fatt de']
question is Wach Yasin mrahch tagini wa9il resopnse is ['ana b3tht m3ana']
question is Oui blk khedwa resopnse is ['']
question is msh inta resopnse is ['nta']
question is Mwlfine yalebo jeu possission lyouma lala elbiha resopnse is ['5lass m3ana we7d']
question is 3jbtk coupa kho ? resopnse is ['dok']
question is Aya Rigel la resopnse is ['oumb3ed fl']
question is Mysra walo resopnse is ['wla bzef 7ab ou hada 7ab ki']
question is Sou1al t3 mamassayne resopnse is ['9dah ou fatt m3ana']
question is Dayman haka m3ahom resopnse is ['fatt f fl fatt m3ana ou 9dah']
question is Ab3tli nchofk resopnse is ['ki 9dah']
question is W yrb ysporithm f houmat resopnse is ['5lass m3ana m3ana']
question is L karyar resopnse is ['aihe']
question is Wahd fina 3ndo cnx 3yana resopnse is ['5lass m3ana aya']
question is Ma9bil ana dkhalt nta khragt resopnse is ['fatt fl m3ana']
question is Wachnoh hada resopnse is ['sa7it hani b3tht']
question is Lo5rin yjo resopnse is ['les']
question is Rak fahm flsafa ? resopnse is ['hani nshouf 7ab de ghir jamber ou 9dah']
question is Matkhafch resopnse is ['5lass fatt de ki berk 7ab fl']
question is Khrj 3adl mn group resopnse is ['aihe ghdwa 9dah we7d we7d']
question is Mwalfin 3la 8 7na resopnse is ['lala ida nshouf']
question is Valhala? resopnse is ['5lass']
question is Balgika ta3 zbi resopnse is ['lah']
question is M3labalich resopnse is ['3la ta3 9dah berk jamber']
question is Bayna resopnse is ['lala 9dah fl f']
question is 9ali ali resopnse is ['hani nshouf men les f']
question is Aya ok hbb resopnse is ['ta3 fatt de']
question is Oumba3d resopnse is ['lah fatt']
question is Nkolk rir 3awad at9ol resopnse is ['7ab']
question is Match resopnse is ['dok']
question is Ih resopnse is ['aya shared tl3b joueurs']
question is Lala ta3 3rbya 3ndna ou zaki mwlf ydirhom ana m3rftch resopnse is ['9dah fl ki ta3 fatt']
question is Alhumdulilah resopnse is ['wesh 5o story. fiha']
question is Wach yacine resopnse is ['wesh nshouf']
question is Tsma main3exe? resopnse is ['aya']
question is Ana wlo resopnse is ['jamber m3ana men message ta3 jamber m3ana m3ana men kipa ki fatt fatt de f']
question is Dcr resopnse is ['asm3 ghdwa ra7 jamber m3ana m3ana 3la 9dah']
question is Tahat kontar villarreal resopnse is ['aya']
question is Mnoderch nji resopnse is ['wesh 5o']
question is Oui resopnse is ['ida 9dah nl3bou joueurs']
question is Wechnoh resopnse is ['sa7it b3tht']
question is Wlh yawo wlh ma jour dok ida hada li raho fi rasi dok n9olo rak thrch hada jour resopnse is ['nta 9dah we7d we7d ou gardien']
question is Navigit jeour resopnse is ['aihe']
question is jbtha resopnse is ['aya rah match']
question is ghodoa ntlagao ya chbab resopnse is ['hhh']
question is Ok resopnse is ['lah fatt ta3 hhh']
question is Ana nekhdem w ntoma te9raw resopnse is ['aya ga3 7ab ta3 fi nta']
question is Nji resopnse is ['3la 9dah']
question is Oki resopnse is ['asm3 shared nl3bou ghdwa men']
question is Ana racist tanit resopnse is ['ghdwa nta fatt']
question is njozo 3la ilyes resopnse is ['nl3bou']
question is 3bdo 9ali ana hsbtli 3la el ballon resopnse is ['aya ki 7ab we7d ta3 3la 9dah men ida 9dah men message']
question is Se9siha resopnse is ['asm3 ki fatt de fi jamber']
question is Hy 3ndhom paga resopnse is ['hhh']
question is mi sah zenji resopnse is ['5lass']
question is Hhh nokya resopnse is ['5lass m3ana']
question is Khlas nji resopnse is ['rigle ida nji 7ab 3la 9dah']
question is Dok nchof blak sah resopnse is ['ok']
question is Aih haka mdernash resopnse is ['5lass']
question is Aya hmdlh resopnse is ['3la 7ab ana b3tht']
question is Yaw makontch sbah f l grop habo yles9oli inas resopnse is ['5lass fatt de m3ana fatt de de message de']
question is Lala resopnse is ['ana ida 9dah nji jamber fi']
question is Chekon hadi resopnse is ['5lass m3ana bzef']
question is Tma sahel resopnse is ['ou rigle dok']
question is Yak ri daira al motalatiya ???? resopnse is ['aya']
question is Jani ana resopnse is ['ana nji fatt']
question is Ou li marka conet tottenham resopnse is ['lah lah ta3 9dah fi nl3bou jamber ta3 fatt']
question is S3ib?? resopnse is ['ta3 9dah fatt']
question is Dok tchof resopnse is ['rigle']
question is Hadi tl3t Visual Studio brk resopnse is ['fatt li jamber men message m3ana']
question is d5elt resopnse is ['9dah fatt']
question is Wach kemelt moraja3a resopnse is ['ana']
question is 3lablhom resopnse is ['ta3 ida les f']
question is Nta resopnse is ['hada nta nji match']
question is Commemme resopnse is ['aya']
question is Omba3d resopnse is ['ok']
question is 4 resopnse is ['ok 3lbali ga3 m3ana de ou nji']
question is Ma3lich ma3lich lmara ljaya arsonal match wa3ar resopnse is ['li f les fatt']
question is Rigl resopnse is ['hani b3tht fatt']
question is Ok resopnse is ['nji ghdwa']
question is AYA DISCORD resopnse is ['nta']
question is R7t 3nd w3rab resopnse is ['']
question is 3lh resopnse is ['5lass m3ana m3ana']
question is 3lah resopnse is ['nl3bou']
question is Ygi ydir gardien resopnse is ['7ab']
question is Lina wigila ih resopnse is ['ta3 9dah wla']
question is w9tach tbda resopnse is ['hani 9dah']
question is 9alk hasan mahoch onlin resopnse is ['ou dok 9dah m3ana']
question is Wlh ya 5o resopnse is ['ana ki fatt de de fatt de ra7 jamber']
question is Cv resopnse is ['aya nta']
question is 5 ntla9aw resopnse is ['ok']
question is Meme basabt resopnse is ['jamber men ghir les joueurs']
question is Y5oo ab3tli wch drto ga3 fl motatlyat 3nde malya resopnse is ['ana b3tht m3ana m3ana bzef rah bash fatt wla 7ab ana b3tht mashi 9dah']
question is Oki w sm7li kho resopnse is ['fl f']
question is za3ma nta se9si w howa yjaweb resopnse is ['5lass m3ana']
question is Okiii asm3 tl3nnna 3lammmna kho resopnse is ['5lass ga3 wla lala']
question is Oky aya omba3d kho resopnse is ['']
question is Nchof hassan ou kamel ? resopnse is ['9dah m3ana m3ana ou 5o 7ab we7d']
question is Mi tzid teb3atli t9oli voti ntiyahlk resopnse is ['fatt fatt']
question is Machkitch nji resopnse is ['b3tht 7ab']
question is Saha 3idk resopnse is ['asm3 da5le de fi gardien m3a f ki fatt hhh 9dah']
question is Zwamel resopnse is ['9dah men message ou 9dah fl men jamber m3ana']
question is 9 officiel resopnse is ['m3a we7d']
question is Byna hbb mrc resopnse is ['asm3 b3tht men ki jamber m3ana message']
question is thabha resopnse is ['rigle lala']
question is B3etlek resopnse is ['wesh rah fatt']
question is Easy lina 3adi resopnse is ['5lass fl story.']
question is 3la 17:00 resopnse is ['ok']
question is Tlagi resopnse is ['nl3bou f les fatt']
question is ?? resopnse is ['mzal wesh 5o 7ab']
question is Oui resopnse is ['ana 5o ki fi']
question is Yji Za3ma !! resopnse is ['ana nchlh gardien 3la ida nji match we7d']
question is Zouj pinaltiyat resopnse is ['asm3 shared nta 9dah']
question is Wach rak dir dok resopnse is ['3la']
question is W khlass resopnse is ['ana nji jamber m3ana']
question is Abdo resopnse is ['rigle']
question is raho yselem 3lik resopnse is ['sa7it']
question is Mhbol ya zh resopnse is ['ki fatt de']
question is Mana9darch nji resopnse is ['aya']
question is Thab dji Liya nhfflk tahfifa tae l3id arwah resopnse is ['fatt bash jamber men message fatt']
question is Wach 9otlo resopnse is ['fatt gardien we7d']
question is Ok dok ndkhl ldar nb3tlk resopnse is ['ok']
question is Roh chkii resopnse is ['aya nshouf']
question is Ya 9hab hayodohom lsahra resopnse is ['nshouf les bzef jamber']
question is Ok resopnse is ['nta 9dah fatt fl']
question is Man3rf resopnse is ['wesh 5o nta nji']
question is ? resopnse is ['']
question is Manrosh sbah bkri resopnse is ['n5rj m3ana men message m3ana']
question is Saha l9ari resopnse is ['5lass joueurs']
question is Nchlh khu resopnse is ['wesh 5o']
question is Asm3 yakho resopnse is ['ok']
question is 47/53 resopnse is ['hani ra7 7ab m3ana ta3 fatt']
question is W drahm ?? resopnse is ['lala 9dash']
question is cv resopnse is ['aya nta']
question is Sayd resopnse is ['nshouf wla']
question is Wach yasine resopnse is ['wesh 5o']
question is w aladin resopnse is ['ok']
question is Ih ylzem mnhalbohomch n3amrolhom chakra resopnse is ['fiha fatt de']
question is Wkta nzido nal3bo resopnse is ['tshou wla 2']
question is Toi resopnse is ['rah 7ab m3ana m3ana']
question is Had lyamat nchdo crino resopnse is ['rigle']
question is Erftni* resopnse is ['aihe shared li l3am m3ana fatt les joueurs']
question is Ih nsbrou khir resopnse is ['ok']
question is Nkhdam la3chia w nkaml jwayah 6h resopnse is ['nji tl3b fl m3ana fl']
question is Ih resopnse is ['tshouf hada 9dash men fatt']
question is Hdak m3ndich wlah lokan s9sito resopnse is ['ok']
question is Chrfawi resopnse is ['asm3 nta fatt ta3 gardien']
question is Aw resopnse is ['dok 7ab m3ana bzef']
question is M3A LES MATH2L2M resopnse is ['']
question is Sahit resopnse is ['5lass']
question is Ok resopnse is ['aya']
question is F stade kho direct wla f tram resopnse is ['ok']
question is yacine resopnse is ['oui']
question is Yacin atini insta ta3 mohe li ydire m3k lvoil resopnse is ['ki bash fatt']
question is Tji tl3ab resopnse is ['nta']
question is Adkhol resopnse is ['aihe']
question is Ih resopnse is ['joueurs']
question is Lik yakho resopnse is ['les']
question is chkn ge3 awjey resopnse is ['']
question is Nchalh fiha 5irr mkch ktar mn hakaa resopnse is ['nchlh 9dah ghdwa 9dah m3ana ki ou 7ab m3ana']
question is Smhli hbb mkontch resopnse is ['rigle 5o']
question is F(x)=X2 resopnse is ['f']
question is Wllah mana9dar yakho resopnse is ['ok']
question is Li hya resopnse is ['5lass m3ana fl ta3']
question is 9et yebloki khirmenek resopnse is ['hhh 7ab m3ana m3ana']
question is 3ndi frimpog resopnse is ['lah 3la']
question is Ombaeda resopnse is ['nshouf fatt fi jamber 3la 9dah']
question is Mathatbnich resopnse is ['3la fatt wla 9dah']
question is L= erreur hhhhhhhh resopnse is ['dok 9dah bash men']
question is M3amen nla3bo hna !! resopnse is ['ana nta 9dah de fl m3ana']
question is Arwah rana raihyn resopnse is ['hani nshouf']
question is . resopnse is ['aihe fiha ida 9dah we7d we7d fatt men']
question is Ma3lich jibo 15mil resopnse is ['dok ghdwa nl3bou kipa jamber fl de']
question is Yakho kifah resopnse is ['ana 9dah 7ab']
question is Ig resopnse is ['li fatt ana 9dah fl']
question is Laiziz resopnse is ['ok nji']
question is Analyse w chwia triciti resopnse is ['ana rah fatt de m3ana']
question is Oki resopnse is ['nl3bou les jamber bash']
question is Lala sahbi resopnse is ['5lass']
question is Oki derrt hsabi rahi rmigla l kippa resopnse is ['asm3 nl3bou nshouf m3ana']
question is wla lala ?? resopnse is ['']
question is Hna ma3endnach ga3 grp resopnse is ['lala 9dah m3ana']
question is Rigl rja3li bah noollhom ida nla3bo wla lala resopnse is ['ana nta wesh 5o 3la ghdwa fatt m3ana']
question is Bayna resopnse is ['lah ra7 9dah m3ana m3ana message']
question is Ok resopnse is ['asm3 shared']
question is Okii nchallah resopnse is ['5lass we7d']
question is Ghdwa nchofo kifah resopnse is ['rigle']
question is M3lich m3lich l3chiya nchofokom m3a Atletico resopnse is ['9dah m3ana men joueurs nshouf we7d ida nshouf']
question is Boudaoui li yslh resopnse is ['5lass li rah 7ab nl3bou']
question is Oui resopnse is ['nta 9dah li']
question is Wlhakayn ya yacin resopnse is ['nl3bou f fl f we7d']
question is Islam 9alo 3liya resopnse is ['5lass nji 7ab fi nshouf fi jamber fi jamber f f']
question is N5srooo resopnse is ['sa7it']
question is Ki tebda eb3atli wach rah dir resopnse is ['aya shtha']
question is Gdwa yak contre aylan resopnse is ['ok']
question is Meme howa 9ali ywali resopnse is ['ki nji']
question is Cv resopnse is ['aya']
question is Mamdolish resopnse is ['fatt m3ana']
question is Aya t3awd resopnse is ['aya']
question is hdoma resopnse is ['nl3bou wla 9dah']
question is Lah yslmk yasine bsa7tkm resopnse is ['sa7it']
question is Ma3lich sa7 nta b3id resopnse is ['fatt de']
question is Tbanli carier wla ain raya resopnse is ['fatt m3ana fi nshouf']
question is Sahit resopnse is ['asm3']
question is Samsoung achri wala radmi resopnse is ['hani bash jamber']
question is Hta y9olk 3ibart lhd l3am resopnse is ['sa7it']
question is Wla hadok ta3 kastor resopnse is ['lah li li']
question is Tdiha resopnse is ['rigle']
question is Yacine yakho resopnse is ['sa7it']
question is wach yacine resopnse is ['wesh']
question is Mafhmtch wch 9otli resopnse is ['fatt de bash']
question is ? resopnse is ['hhh f']
question is Hhh resopnse is ['9dah wesh nji']
question is Dire englais resopnse is ['aihe']
question is Na9ssaa haja resopnse is ['wla gardien']
question is Nrml njibo bastita wkhlas resopnse is ['asm3 ki 9dah']
question is Nroho resopnse is ['ida 9dah fl nji']
question is Lala resopnse is ['hada']
question is Aya mlih resopnse is ['ki 9dah m3ana f message shwya']
question is Nchlhh Had lkhtra maysra wlo resopnse is ['asm3 shared']
question is Nmhtk resopnse is ['lala nshouf les joueurs m3ana de wla nta nshouf joueurs']
question is fekerni w neb3atlek kho resopnse is ['lah lah']
question is Aya yacin resopnse is ['9dah f f fi jamber']
question is Win? resopnse is ['3la']
question is Khirmen madiya3 we9tk resopnse is ['fiha']

In [61]:
y_test

<tf.Tensor: shape=(2703, 32), dtype=int64, numpy=
array([[ 107,    1, 1209, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,   10, 2656, ...,    0,    0,    0],
       ...,
       [  33,   51,    0, ...,    0,    0,    0],
       [1426,  277,   28, ...,    0,    0,    0],
       [   1,   67,    0, ...,    0,    0,    0]])>

In [62]:
from nltk.translate.bleu_score import sentence_bleu

references = []
candidates = []

for i in range(len(y_test)):
    ref_seq = seq_to_text([y_test[i]], answer_vocab)[0].split()
    pred_seq = seq_to_text([pred[i]], answer_vocab)[0].split()
    references.append([ref_seq])
    candidates.append(pred_seq)

In [63]:
bleu_scores = []

for ref, cand in zip(references, candidates):
    score = sentence_bleu(ref, cand)
    bleu_scores.append(score)

print("Average BLEU:", sum(bleu_scores)/len(bleu_scores))

Average BLEU: 0.0010914320707007578

/usr/local/lib/python3.12/dist-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/usr/local/lib/python3.12/dist-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/usr/local/lib/python3.12/dist-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)