In [302]:
!git clone https://github.com/yacinemebarki/talk_like_me_gpt

fatal: destination path 'talk_like_me_gpt' already exists and is not an empty directory.

In [303]:
import pandas as pd
import numpy as np

In [304]:
df=pd.read_csv("/content/talk_like_me_gpt/data/message.csv")
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
88732,ÙØ´ÙÙØ§,Yacine Mebarki,1665091715875
88733,ØØØØ,Yacine Mebarki,1665091659314
88734,ÙØ§Ø³ÙÙ,Instagram User,1665091578941
88735,ÙØ´ Ø¹Ø¨Ø¯Ù,Yacine Mebarki,1665000590565
88736,Instagram User sent an attachment.,Instagram User,1665000509441

In [305]:
print(len(np.unique(df["sender"])))

203

In [306]:
print(len(np.unique(df["content"])))

53172

In [307]:
import re

def clean(mes):
  pattern = re.compile(r"(http[s]?://\S+)|[^\x00-\x7F]")
  return bool(pattern.search(mes))

In [308]:
df=df[df["content"].apply(clean)==False]
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
88718,Mat7rshsh,Yacine Mebarki,1663535817836
88719,Instagram User sent an attachment.,Instagram User,1666436431597
88720,Instagram User sent an attachment.,Instagram User,1666254455735
88721,Instagram User sent an attachment.,Instagram User,1666252975962
88736,Instagram User sent an attachment.,Instagram User,1665000509441

In [309]:
df=df.reset_index()
df

,index,content,sender,time
0,0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,2,Lala,Yacine Mebarki,1750440185876
3,3,Wesh 5o,Yacine Mebarki,1750440085631
4,4,You missed an audio call,Instagram User,1750440059051
...,...,...,...,...
66156,88718,Mat7rshsh,Yacine Mebarki,1663535817836
66157,88719,Instagram User sent an attachment.,Instagram User,1666436431597
66158,88720,Instagram User sent an attachment.,Instagram User,1666254455735
66159,88721,Instagram User sent an attachment.,Instagram User,1666252975962
66160,88736,Instagram User sent an attachment.,Instagram User,1665000509441

In [310]:
df=df.drop(columns=["index"])
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
66156,Mat7rshsh,Yacine Mebarki,1663535817836
66157,Instagram User sent an attachment.,Instagram User,1666436431597
66158,Instagram User sent an attachment.,Instagram User,1666254455735
66159,Instagram User sent an attachment.,Instagram User,1666252975962
66160,Instagram User sent an attachment.,Instagram User,1665000509441

In [311]:
df.head(10)

                                     content          sender           time
0  Sma7li ykho mnkonsh fdar flil 3endi shghl  Yacine Mebarki  1752245800635
1                          Yacine Lyom 3aa 9  Instagram User  1752244626530
2                                       Lala  Yacine Mebarki  1750440185876
3                                    Wesh 5o  Yacine Mebarki  1750440085631
4                   You missed an audio call  Instagram User  1750440059051
5                         Audio call started  Instagram User  1750440042297
6                                      Yacin  Instagram User  1750440008927
7                            3endi shghl dok  Yacine Mebarki  1750087644305
8                                  Man9dersh  Yacine Mebarki  1750087636879
9               Ntl3o oumb3d nontrino chwiya  Instagram User  1750078313534

In [312]:
df["content"]

0        Sma7li ykho mnkonsh fdar flil 3endi shghl
1                                Yacine Lyom 3aa 9
2                                             Lala
3                                          Wesh 5o
4                         You missed an audio call
                           ...
66156                                    Mat7rshsh
66157           Instagram User sent an attachment.
66158           Instagram User sent an attachment.
66159           Instagram User sent an attachment.
66160           Instagram User sent an attachment.
Name: content, Length: 66161, dtype: object

In [313]:
print(len(df[df["content"]=="You missed an audio call"]))
count=df['content'].str.contains('sent an attachment', case=False, na=False).sum()
print(count)
print(len(df[df["content"]=="You started an audio call"]))

290
8938
391

In [314]:
df=df[~(df["content"].str.contains('sent an attachment',case=False,na=False)|
      (df["content"]=="You missed an audio call")|
      (df["content"]=="You started an audio call")|
        (df["content"]=="Audio call started")|
        (df["content"]=="Audio call ended")|
        (df["content"].str.contains('started an audio call',case=False,na=False))|
        (df["content"]=="Liked a message"))]
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
6,Yacin,Instagram User,1750440008927
...,...,...,...
66152,Zino ousama tan,Wð©¸,1663535934578
66153,Rayne than darha story,Yacine Mebarki,1663535914924
66154,Makach mnha,Wð©¸,1663535862990
66155,Hhh,Wð©¸,1663535849006
66156,Mat7rshsh,Yacine Mebarki,1663535817836

In [315]:
df=df.reset_index()
df=df.drop(columns=["index"])
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,Yacin,Instagram User,1750440008927
...,...,...,...
53278,Zino ousama tan,Wð©¸,1663535934578
53279,Rayne than darha story,Yacine Mebarki,1663535914924
53280,Makach mnha,Wð©¸,1663535862990
53281,Hhh,Wð©¸,1663535849006
53282,Mat7rshsh,Yacine Mebarki,1663535817836

In [316]:
df['next_content'] = df['content'].shift(-1)
df['next_sender'] = df['sender'].shift(-1)

In [317]:
df

,content,sender,time,next_content,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
1,Yacine Lyom 3aa 9,Instagram User,1752244626530,Lala,Yacine Mebarki
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
4,Yacin,Instagram User,1750440008927,3endi shghl dok,Yacine Mebarki
...,...,...,...,...,...
53278,Zino ousama tan,Wð©¸,1663535934578,Rayne than darha story,Yacine Mebarki
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53280,Makach mnha,Wð©¸,1663535862990,Hhh,Wð©¸
53281,Hhh,Wð©¸,1663535849006,Mat7rshsh,Yacine Mebarki
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [318]:
df.rename(columns={"content":"answer","next_content":"message"}, inplace=True)
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
1,Yacine Lyom 3aa 9,Instagram User,1752244626530,Lala,Yacine Mebarki
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
4,Yacin,Instagram User,1750440008927,3endi shghl dok,Yacine Mebarki
...,...,...,...,...,...
53278,Zino ousama tan,Wð©¸,1663535934578,Rayne than darha story,Yacine Mebarki
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53280,Makach mnha,Wð©¸,1663535862990,Hhh,Wð©¸
53281,Hhh,Wð©¸,1663535849006,Mat7rshsh,Yacine Mebarki
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [319]:
df=df[df["sender"]=="Yacine Mebarki"]
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
5,3endi shghl dok,Yacine Mebarki,1750087644305,Man9dersh,Yacine Mebarki
6,Man9dersh,Yacine Mebarki,1750087636879,Ntl3o oumb3d nontrino chwiya,Instagram User
...,...,...,...,...,...
53273,Wesh wadoud tji 3shya,Yacine Mebarki,1731156585337,Ok,Yacine Mebarki
53274,Ok,Yacine Mebarki,1685647730830,B3atilou,Wð©¸
53277,Zinou hbt m3aya lljam3,Yacine Mebarki,1663535955943,Zino ousama tan,Wð©¸
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [320]:
df=df[df["next_sender"]!="Yacine Mebarki"]
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
6,Man9dersh,Yacine Mebarki,1750087636879,Ntl3o oumb3d nontrino chwiya,Instagram User
8,Lala,Yacine Mebarki,1750078181154,Makch tontrini,Instagram User
10,Wlah walou mkash ga3,Yacine Mebarki,1750078074006,Yacin kach match,Instagram User
...,...,...,...,...,...
53271,Asm3 rani fi plassa champ na9ss,Yacine Mebarki,1731520839382,Ih,Wð©¸
53274,Ok,Yacine Mebarki,1685647730830,B3atilou,Wð©¸
53277,Zinou hbt m3aya lljam3,Yacine Mebarki,1663535955943,Zino ousama tan,Wð©¸
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,Wð©¸
53282,Mat7rshsh,Yacine Mebarki,1663535817836,None,None

In [321]:
df=df.dropna(subset=['message', 'answer'])

In [322]:
df.iloc[30:50]

,answer,sender,time,message,next_sender
90,Rigle,Yacine Mebarki,1765919575586,Fiha,â­ï¸
93,Asm3 ji tl3b ghdwa and ali 3la 20,Yacine Mebarki,1765919545080,Ni khrg deka,â­ï¸
96,Ana then haji 5arj,Yacine Mebarki,1759604173430,Aya riglha khu,â­ï¸
99,Aya rigle fiha,Yacine Mebarki,1759596864250,Nji,â­ï¸
102,Ya5i rouf yji,Yacine Mebarki,1759596848247,Riglha shby,â­ï¸
104,aya oumb3ed ntl9awe fstad direct,Yacine Mebarki,1759596796160,Rigkha khu,â­ï¸
111,Wesh ramzi,Yacine Mebarki,1759595591747,Aya riglha hbb,â­ï¸
113,Dok nshouf Ida ran 9l men 9 3ytlou,Yacine Mebarki,1741611849180,Ay yasine neayt raouf na3mni yji yl3b m3ana,â­ï¸
117,Kima malf mour l3asser,Yacine Mebarki,1741552887267,39dach,â­ï¸
122,Aya rigle,Yacine Mebarki,1740585493897,9al wsdoud ih,â­ï¸
126,Ok,Yacine Mebarki,1740578852304,Aya ruglha ana nji,â­ï¸
130,Ana rayan,Yacine Mebarki,1740578821157,Chkn rah jay ga3,â­ï¸
136,Learn,Yacine Mebarki,1750704300508,You sent a private reply to a comment on your ...,Danica Simic
139,Send me the link!,Yacine Mebarki,1757716600930,You sent a private reply to a comment on your ...,Loper App
145,Lk7la ana marhish ji,Yacine Mebarki,1663262915870,Hadik demi,MÃ¸ HÃ£ MÃ¸ HÄ
148,Ta3i t9t3t,Yacine Mebarki,1663250080369,Ida ma3lich tssalafhali,MÃ¸ HÃ£ MÃ¸ HÄ
154,hadi mashi plansha bash tplani biha,Yacine Mebarki,1637414816212,Alg,rÃ¡Ã¿an mhd's
160,hmdlh,Yacine Mebarki,1634213700303,Cv,rÃ¡Ã¿an mhd's
163,Wesh,Yacine Mebarki,1634142673458,rayanmhds changed the theme to J Balvin,rÃ¡Ã¿an mhd's
165,HMDLH NTA,Yacine Mebarki,1633983421449,Cv,rÃ¡Ã¿an mhd's

In [323]:
from tensorflow.keras import layers,models
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [324]:
from sklearn.model_selection import train_test_split

In [325]:
df=df.reset_index()
df=df.drop(columns=["index"])

In [326]:
x=df["answer"]
y=df["message"]

In [327]:
tok_m=Tokenizer()
tok_a=Tokenizer()
tok_m.fit_on_texts(x)
tok_a.fit_on_texts(y)

In [328]:
x_seq=tok_m.texts_to_sequences(x)
y_seq=tok_a.texts_to_sequences(y)

In [329]:
x_seq=pad_sequences(x_seq,maxlen=32)
y_seq=pad_sequences(y_seq,maxlen=32)

In [330]:
x_train,x_test,y_train,y_test=train_test_split(x_seq,y_seq,test_size=0.2,random_state=42)

In [340]:
model=models.Sequential()
model.add(layers.Embedding(input_dim=len(tok_m.word_index)+1,output_dim=32))
model.add(layers.SimpleRNN(64,return_sequences=True))
model.add(layers.TimeDistributed(layers.Dense(len(tok_a.word_index)+1,activation="softmax")))

In [341]:
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy")

In [342]:
model.fit(x_seq,y_seq,epochs=5,batch_size=32)

Epoch 1/5
423/423 ━━━━━━━━━━━━━━━━━━━━ 375s 877ms/step - loss: 3.4793
Epoch 2/5
423/423 ━━━━━━━━━━━━━━━━━━━━ 363s 859ms/step - loss: 0.9565
Epoch 3/5
423/423 ━━━━━━━━━━━━━━━━━━━━ 354s 838ms/step - loss: 0.9475
Epoch 4/5
423/423 ━━━━━━━━━━━━━━━━━━━━ 363s 859ms/step - loss: 0.9279
Epoch 5/5
423/423 ━━━━━━━━━━━━━━━━━━━━ 375s 843ms/step - loss: 0.9356