In [1]:
import numpy as np
import pandas as pd

In [2]:
path="/home/yacine10/talk_like_me_gpt/data/train-00000-of-00001.csv"
data=pd.read_csv(path)
data

,english,darija,includes_arabizi
0,He [Wales] basically lied to us from the start...,كذب ويلز علينا بشكل أساسي من الأول. أولاً منين...,False
1,I was moved every time we did a rehearsal on t...,كنتأثر من قلبي كل مرة كنديرو هاد التدريب على ه...,False
2,"She’s very cute and sings quite well, too, he ...",قال تبعا لواحد النص ديال المؤتمر الصحفي أنها ز...,False
3,They are cooler than the surrounding surface i...,هوما باردين كتَر من السطح اللي داير بيهم فالنه...,False
4,This is not going to be goodbye. This is the c...,هادا مغيكونش وداع هادا هو نهاية ديال هاد الفصل...,False
...,...,...,...
16084,that suits me,hadchi msllkni,True
16085,it's on you,3la 7sabk,True
16086,shame on you,Lah i3Tik matakol,True
16087,properly,3la 799o o Tri9o,True
16088,frequently,miraran wa tikraran,True

In [3]:
arabizi=data[data["includes_arabizi"]==True]
print("the number of arabizi sentence=",len(arabizi))

the number of arabizi sentence= 10062

In [4]:
data=data[data["includes_arabizi"]==True]
data.reset_index()

,index,english,darija,includes_arabizi
0,6027,"They're hiding something, I'm sure!","homa mkhbbyin chi haja, ana mti99en!",True
1,6028,It's obvious they're trying to keep their cool.,bayna homa tay7awlo ib9aw mbrrdin.,True
2,6029,the hotels don't seem very comfortable.,loTilat mabaynach fihom mori7in bzzaf.,True
3,6030,he is probably about to be laid off by head of...,ghaliban ghayjrriw 3lih mn lkhdma!,True
4,6031,of course he's depressive!,Tab3an rah mkta2eb!,True
...,...,...,...,...
10057,16084,that suits me,hadchi msllkni,True
10058,16085,it's on you,3la 7sabk,True
10059,16086,shame on you,Lah i3Tik matakol,True
10060,16087,properly,3la 799o o Tri9o,True
10061,16088,frequently,miraran wa tikraran,True

In [5]:
data=data[["darija","english"]]
data=data.reset_index()

In [6]:
data=data.drop(columns=["index"])
data

,darija,english
0,"homa mkhbbyin chi haja, ana mti99en!","They're hiding something, I'm sure!"
1,bayna homa tay7awlo ib9aw mbrrdin.,It's obvious they're trying to keep their cool.
2,loTilat mabaynach fihom mori7in bzzaf.,the hotels don't seem very comfortable.
3,ghaliban ghayjrriw 3lih mn lkhdma!,he is probably about to be laid off by head of...
4,Tab3an rah mkta2eb!,of course he's depressive!
...,...,...
10057,hadchi msllkni,that suits me
10058,3la 7sabk,it's on you
10059,Lah i3Tik matakol,shame on you
10060,3la 799o o Tri9o,properly
10061,miraran wa tikraran,frequently

In [7]:
print(len(np.unique(data["darija"])))
print(len(np.unique(data["english"])))

9901
9521

In [8]:
import tensorflow as tf

2026-03-06 16:52:54.532800: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-06 16:52:55.400020: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-06 16:53:01.857088: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [9]:
from tensorflow.keras import layers,models

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [12]:
print(dir(Tokenizer))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_api_export_path', '_api_export_symbol_id', 'fit_on_sequences', 'fit_on_texts', 'get_config', 'sequences_to_matrix', 'sequences_to_texts', 'sequences_to_texts_generator', 'texts_to_matrix', 'texts_to_sequences', 'texts_to_sequences_generator', 'to_json']

In [13]:
x=data["darija"]
y=data["english"]

In [14]:
tk_darja=Tokenizer()
tk_darja.fit_on_texts(x)
tk_english=Tokenizer()
tk_english.fit_on_texts(y)

In [15]:
x_sequence=tk_darja.texts_to_sequences(x)
y_sequence=tk_english.texts_to_sequences(y)

In [16]:
print(dir(pad_sequences))

['__annotations__', '__builtins__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_api_export_path', '_api_export_symbol_id']

In [17]:
x_sequence=pad_sequences(x_sequence,maxlen=32)
y_sequence=pad_sequences(y_sequence,maxlen=32)

In [18]:
x_sequence=np.array(x_sequence)
y_sequence=np.array(y_sequence)

In [19]:

x_train,x_test,y_train,y_test=train_test_split(x_sequence,y_sequence,test_size=0.2,random_state=42)

In [20]:
print(dir(layers))

['Activation', 'ActivityRegularization', 'Add', 'AdditiveAttention', 'AlphaDropout', 'Attention', 'AugMix', 'AutoContrast', 'Average', 'AveragePooling1D', 'AveragePooling2D', 'AveragePooling3D', 'AvgPool1D', 'AvgPool2D', 'AvgPool3D', 'BatchNormalization', 'Bidirectional', 'CategoryEncoding', 'CenterCrop', 'Concatenate', 'Conv1D', 'Conv1DTranspose', 'Conv2D', 'Conv2DTranspose', 'Conv3D', 'Conv3DTranspose', 'ConvLSTM1D', 'ConvLSTM2D', 'ConvLSTM3D', 'Convolution1D', 'Convolution1DTranspose', 'Convolution2D', 'Convolution2DTranspose', 'Convolution3D', 'Convolution3DTranspose', 'Cropping1D', 'Cropping2D', 'Cropping3D', 'CutMix', 'Dense', 'DepthwiseConv1D', 'DepthwiseConv2D', 'Discretization', 'Dot', 'Dropout', 'ELU', 'EinsumDense', 'Embedding', 'Equalization', 'Flatten', 'FlaxLayer', 'GRU', 'GRUCell', 'GaussianDropout', 'GaussianNoise', 'GlobalAveragePooling1D', 'GlobalAveragePooling2D', 'GlobalAveragePooling3D', 'GlobalAvgPool1D', 'GlobalAvgPool2D', 'GlobalAvgPool3D', 'GlobalMaxPool1D', 'GlobalMaxPool2D', 'GlobalMaxPool3D', 'GlobalMaxPooling1D', 'GlobalMaxPooling2D', 'GlobalMaxPooling3D', 'GroupNormalization', 'GroupQueryAttention', 'HashedCrossing', 'Hashing', 'Identity', 'Input', 'InputLayer', 'InputSpec', 'IntegerLookup', 'JaxLayer', 'LSTM', 'LSTMCell', 'Lambda', 'Layer', 'LayerNormalization', 'LeakyReLU', 'Masking', 'MaxNumBoundingBoxes', 'MaxPool1D', 'MaxPool2D', 'MaxPool3D', 'MaxPooling1D', 'MaxPooling2D', 'MaxPooling3D', 'Maximum', 'MelSpectrogram', 'Minimum', 'MixUp', 'MultiHeadAttention', 'Multiply', 'Normalization', 'PReLU', 'Permute', 'Pipeline', 'RMSNormalization', 'RNN', 'RandAugment', 'RandomBrightness', 'RandomColorDegeneration', 'RandomColorJitter', 'RandomContrast', 'RandomCrop', 'RandomElasticTransform', 'RandomErasing', 'RandomFlip', 'RandomGaussianBlur', 'RandomGrayscale', 'RandomHeight', 'RandomHue', 'RandomInvert', 'RandomPerspective', 'RandomPosterization', 'RandomRotation', 'RandomSaturation', 'RandomSharpness', 'RandomShear', 'RandomTranslation', 'RandomWidth', 'RandomZoom', 'ReLU', 'RepeatVector', 'Rescaling', 'Reshape', 'Resizing', 'ReversibleEmbedding', 'STFTSpectrogram', 'SeparableConv1D', 'SeparableConv2D', 'SeparableConvolution1D', 'SeparableConvolution2D', 'SimpleRNN', 'SimpleRNNCell', 'Softmax', 'Solarization', 'SpatialDropout1D', 'SpatialDropout2D', 'SpatialDropout3D', 'SpectralNormalization', 'StackedRNNCells', 'StringLookup', 'Subtract', 'TFSMLayer', 'TextVectorization', 'ThresholdedReLU', 'TimeDistributed', 'TorchModuleWrapper', 'UnitNormalization', 'UpSampling1D', 'UpSampling2D', 'UpSampling3D', 'Wrapper', 'ZeroPadding1D', 'ZeroPadding2D', 'ZeroPadding3D', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'add', 'average', 'concatenate', 'deserialize', 'dot', 'maximum', 'minimum', 'multiply', 'serialize', 'subtract']

In [21]:
print(dir(models))

['Model', 'Sequential', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'clone_model', 'load_model', 'model_from_json', 'save_model']

In [22]:
print(dir(layers.RNN))

['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_trackable_child', '_add_variable_with_custom_getter', '_api_export_path', '_api_export_symbol_id', '_assert_input_compatibility', '_build_at_init', '_build_by_run_for_kwargs', '_build_by_run_for_single_pos_arg', '_check_load_own_variables', '_check_quantize_args', '_check_super_called', '_checkpoint_adapter', '_checkpoint_dependencies', '_clear_losses', '_copy_trackable_to_cpu', '_create_state_variables', '_default_save_signature', '_deferred_dependencies', '_delete_tracking', '_deserialization_dependencies', '_deserialize_from_proto', '_export_to_saved_model_graph', '_flatten_layers', '_float8_call', '_gather_saveables_for_checkpoint', '_get_call_context', '_get_node_attribute_at_index', '_get_own_losses', '_get_regularization_losses', '_gptq_call', '_handle_deferred_dependencies', '_initialize_tracker', '_int4_call', '_int8_call', '_lock_state', '_lookup_dependency', '_maybe_build', '_maybe_config_dropout_masks', '_maybe_initialize_trackable', '_maybe_reset_call_context', '_maybe_reset_dropout_masks', '_name_based_attribute_restore', '_name_based_restores', '_no_dependency', '_not_implemented_error', '_obj_type', '_object_identifier', '_open_name_scope', '_post_build', '_post_track_variable', '_post_untrack_variable', '_preload_simple_restoration', '_quantization_mode_error', '_register_call_context_args', '_resolve_and_populate_arg', '_restore_from_tensors', '_serialize_to_proto', '_serialize_to_tensors', '_set_mask_metadata', '_set_save_spec', '_setattr_hook', '_setattr_tracking', '_tf_api_names', '_tf_api_names_v1', '_track_trackable', '_track_variable', '_trackable_children', '_unconditional_checkpoint_dependencies', '_unconditional_dependency_names', '_unpickle_model', '_untrack_variable', '_update_uid', 'add_loss', 'add_metric', 'add_variable', 'add_weight', 'build', 'build_from_config', 'call', 'compute_dtype', 'compute_mask', 'compute_output_shape', 'compute_output_spec', 'count_params', 'dtype', 'dtype_policy', 'from_config', 'get_build_config', 'get_config', 'get_initial_state', 'get_weights', 'inner_loop', 'input', 'input_dtype', 'input_spec', 'load_own_variables', 'losses', 'metrics', 'metrics_variables', 'non_trainable_variables', 'non_trainable_weights', 'output', 'path', 'quantization_mode', 'quantize', 'quantized_build', 'quantized_call', 'rematerialized_call', 'reset_state', 'reset_states', 'save_own_variables', 'set_weights', 'stateless_call', 'supports_masking', 'symbolic_call', 'trainable', 'trainable_variables', 'trainable_weights', 'variable_dtype', 'variables', 'weights']

In [23]:
model=models.Sequential()
model.add(layers.Embedding(input_dim=len(tk_darja.word_index)+1,output_dim=64,input_length=32))
model.add(layers.SimpleRNN(64,return_sequences=True))
model.add(layers.TimeDistributed(layers.Dense(len(tk_english.word_index)+1, activation="softmax")))

/home/yacine10/.local/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2026-03-06 16:53:08.293901: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [24]:
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy")

In [ ]:
'''model.fit(x_train,y_train,epochs=10)'''

Epoch 1/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 115s 424ms/step - loss: 2.4049
Epoch 2/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 111s 440ms/step - loss: 1.3502
Epoch 3/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 100s 397ms/step - loss: 1.3295
Epoch 4/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 93s 367ms/step - loss: 1.3119
Epoch 5/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 93s 369ms/step - loss: 1.2947
Epoch 6/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 95s 375ms/step - loss: 1.2771
Epoch 7/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 89s 353ms/step - loss: 1.2576
Epoch 8/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 89s 351ms/step - loss: 1.2358
Epoch 9/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 88s 351ms/step - loss: 1.2126
Epoch 10/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 89s 352ms/step - loss: 1.1875

In [ ]:
'''
for text in y_test:
    print(tk_darja.sequences_to_texts([text]))
    id=np.argmax(model.predict(np.expand_dims(text,axis=0)),axis=-1)
    print(tk_english.sequences_to_texts(id))'''

['o imken 3ndi b3d 7da la dyal mra i9dr khayb chno']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
['you a time the the of of to the you']
['wach sma7 achno lel 7aja imkan lia 3tini']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
["you i'm you you to you to to"]
['bghiti f jib kay3jebni']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
['to the work the']
['dyal kif hia achno msta3dda']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
['of you a you you']
['9bal mzyan bli nta lwa9t kolchi 3ndi lla deghya']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
['you to you you you a a you your']
['mn o homa chrab kayna dakchi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
['the the you the a that']
['wach b tkon salam ghadi 3tini']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
["you the be i'm to to"]
['kayn wach knti o ma3ndich chi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
['a you you you the the']
['l wach 7ta rachid rah rasi f dyal iwa walakin machrob']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
['the you you gym and the the of and i']
['wach mazal dyal lflous b7al kandir']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
['you you of you to to']
['taniya ana kaddir ddirha ach 7aja makhasnach']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
['you not very you you you to']
['bach 7aja imkan hna o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step
['you to you here the']
['makayl3bouch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
['a']
['chi ana a9al nkhlik 9bel aykhasna dyal tma ya9dar l lla makan7malch f joz2']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
['a not much you you me of to to the the too the the']
['bach ikono']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
['you me']
['wach fl 3ndak fach lik aflam']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
['you the work to you dogs']
['ah ghadi wj8ou']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
['be very']
['lia l7mar nmchiw laho3lem f llekher']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
['you the to you the the']
['wach 3la f dialk mnin yallah dyal khasni taba9 tta9a walakin 3ndk zine']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
['you you the your to you the to work of you you you']
['bzaf 8na goul walakin ghadi charika khod']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
['you here the you to to the']
['wach bzzaf b l lksida kandn lik o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step
['you good the the them the you and']
['jaya dyali o simana machi nb9aw']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
['you is you me not be']
['bghiti mabghitch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
['to to']
['o l wach nta hada f dyal 2amrika']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
['the you you to the the of']
['bghitini dyali wach 3ndak o ghadi bllati momkin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
['you a you you you to to me']
['wach ila lia ahya']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
['you you you you']
['ta7ed wach wakha lkhdma n3awnak f ssout had']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
['is you you this you the the this']
['ana chno ghadi 7ad machi ana matalan sme3ti']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
["i'm you you to a not sick itself"]
['chi bjoj dima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
['a is you']
['mzyan wach 3la dima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
['is you you you']
['3afak dyal tma khssni f homa walakin dyal yoga']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
['you you to to the the you you much']
['8ad daba wa7ed machi dayer hamdolah nta 7aja onti walakin dyal blmonasaba']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
['is now the a a fast and you you you you you']
['kayn wach 7ta l7ala f 3ndak ah tlflous mn o 3la']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
['a you you a in of sick of and the']
['mzyan kbir o ma3ndich nchof fayt mbrre3']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
['is good and the you you you']
['wach lkhdma f b tta']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
['you this the the a']
['dyalo ila f kat3awd lia lik mandir']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
['is you the the to you you']
['ch7al dakchi m3a nta la dyal lmajmo3a hadchi dyal fa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
['you you to to the the of that of you']
['ykon o chokran ila machi nnas chamal annaho']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
['to the you you not very late and']
['makhddamach 3lach o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
['good you you']
['bzaf ana 7san']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
['you not me']
['rah wa ana dyalk 7san']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
['is i not very to']
['daba fabor']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
['you the']
['o nta walakin kan ghlid annani']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
['you you i the the']
['sghira ay']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
['is you']
['daba dyalk dyal kaml achmn']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
['you you you of you']
['zwina ga3 tal']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
['is to to']
['bach khasna b bghiti rah l3a2ila mawdo3 ba3d']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
['you to the to the the cooking of']
['dyali o 7ta dialk zwin la zwin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
['is and you i to the the']
['wakha dik hadi dyal n9tar7']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
['that a of of']
['wa7d 7it mn machi l ayeh wach lkhdma f awal dyal hmm l7al hia 7ta 8owwa walakin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
['a i the not the i you you the the of time of is is a i']
['8ad ach dyal mankonch 8na ghanmchi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step
['is you you to here the']
['wach tbghi tkon hadi rah l7ayawanat']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
['you you to the a good']
['daba dyalk ghadi kanchof 3lik bsa7 lkhadma nnas']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
['you you to to to you the the']
['3lik tlwe9t chno lik kat9sad nit']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
['you you you you mean a']
['ta7t o n3ref chofo']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
['is the you the']
['oh tmchi oh m3a bghiti tkon hadchi dyal a kbira b khddam mojito 14 3odw']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
["you i'm the to be this of you good in of and and cooking"]
['dyali o bghiti ghadi ntla3 bnsba 3lach kan howwa f 3arf tkon wahd m3a nta']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
['is and to be the to you you is the you to a the of']
['3lik meziana achno lbal bghit makannakolch jani']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
['you good you you to the animals']
['wach fin f 3ndi ghadi 3titini']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
['you you the the to the']
['ana lia bghit zwin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
["i'm i to the"]
['daba ghadi fiha nglso ach 3lik mazyan achno rak ghir la rah fga3 n8ark']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step
['you you to anything you you you you you you a a the of']
['walakin ttani chi ssba7 had ghadi ndir hadchi fr7an bghit lmanga l l2a3mal']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
['is a the this to to this you to good in the']
['wach ki machi 7it makltek 3lach dima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step
['you you not i a you you']
['dyal 7tta ana 7ta ism']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step
['of is not a to']
['kayn gal']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step
['a the']
['bach lmada9 f ngollik']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step
['you a in and']
['haja charab trf f 3ndi tl9na']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
['you the the the the of']
['chwia o 8owwa khayb f hoa had ma3raftch chi bezzaf']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step
['is and a a in the this and you you']
['dyalo ndiro 8ad']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step
['is you this']
['dyalk machi chi ana rah ljow']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
['you not a not not a']
['machi ana dyal compte no9ta']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
['not not of fault of']
['8ad daba ntchawfou']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
['is now you']
['ach la dyal kaml dima lw9t mabghitch kayna dyal charge mlli lmos3ifin daba ssimana']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
['you you of of you you to a of of of the now you']
['dyal flghalib bihom ana 3']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
['of to the a new']
['ban bach hadi o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step
['to a the']
['mti7an mti7an']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
['is beautiful']
['m3a lkhdma matreddedch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step
['the work of']
['o chwiya hakkak imkan men']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step
['the i you you']
['mobtadi2 wach wakha 9adr lia dyalha la dial']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
['is you you you to to a of']
['m3a chwia b l kay3ejbek hadi dyal lmout l liya ah lmakla dyali khas']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
['the of of the the in of and the be a good sir']
['bzaf bila 8ada']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
['you you is']
['hoa had']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
['is this']
['8adchi li 8na kan nhar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
['is a here the the']
['8adchi li 3afak o mn hadi kan tchouf 3ndek ymken']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
['is a please you you the a the the you']
['o nta dyalk ghadi frran']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
['you you to the']
['m3a t9riban la bghitek']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step
['the good and the']
['wach lli tari9a khososan nta 7aja ghir dak']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step
['you you me the you the the to']
['wach 7na lou9id']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
['you you you']
['bzaf ana i9dar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step
['you not to']
['lmakla 8na tsenna 3lach dyal nhar hadchi dyal fchi l ch7al m3a fhmtini f annak ikon me9li oh walakin dyal galiyya']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
['is here the and the the this of to the work the together in to to of and you to']
['wahd nta o kayna walakin dyal maghadi msafer']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step
['is you you a you you you mean']
['bach ttarikh']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
['you a']
['wla ghadi l3chiya l7am o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step
['to to of and']
['kaynin wach chwiya daba aji']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
['is you you now you']
['khayba 3lach dyal takol']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step
['is you you time']
['ana chno restora tbeddel walakin dyal a7san']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step
["i'm you you you you you to"]
['chi lil b7al']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step
['a you a']
['wakha o 3la ghadi lkelb f bghiti ghadi miladek kayna ghadi mkhlou3']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
['i the be the the to be together and to a']
['khayba wa7d']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
['is a']
['8ad hadchi t9der']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
['is that you']
['bzaf tani f n9der ah banjo ana']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
['you of the you you not']
['wach sma7 tl o 3ziz']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
["you i'm you you to"]
['bghit wajda t3llmti']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
['to good and']
['wach lb7er walakin maghadich imta howa f matb9ach dyal f7alna']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
['you a that you to a the pool of and']
['wach ila anna lik chkoun khoya l motir']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
['you you you you to very the your']
['lik rah zwin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
['you you a']
['chi ana kan ktabi lihom dial']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
['a not a is a of']
['wach 3la ghadi tji mti99en makan3rafch ga3 dial']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
['you you be to be very in the']
['dyal takol ana annana f rriyada']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
['of of and i the plane']
['wach lkhdma maths rah kima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
['you this is to you']
['s7i7 we9t jiti rah lkhrin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
['is to to a a']
['kayn ga3 choklat']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step
['a the your']
['wach l7lib drhem dyal n9dar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
['you is sick of and']
['nta o ghadi ghir mezian']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
['you you be be to']
['momkin mzyana dyalk']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
['you is of']
['nta o kindir bezzaf dyal ssrf hadi kan howwa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
['you you you you of time the the is']
['mn o b9at makentich']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
['the the the you']
['mli machi kolchi ndiro 3liyya']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
['you not very that me']
['wach 3lih o chwiya li f mn machi 3lach kan b3id']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
['you you you the you the the a i i to']
['daba makan7malch 8adi mskin s3ib']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
['you you the you you']
['wla dyalk ala walakin ghadi tri9 maddirch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
['you you you to a you']
['ah bghit 8iyya ghadi chriti']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step
['to a be them']
['mzyan o kter walakin dakchi m3a chwia homa ahlan']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
['is and the you you to your and i']
['lktab ana kon']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
['is a and']
['wakha mn machi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
['you not']
['lmakla hia mazyan achno mrida']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step
['is is good you very']
['wach fl chwiya li f 3ndo o ach wach lli wach jjame3 chi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
['you the the the the a and you you you you mean a']
['wla yjiw dar fach']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
['the of and']
['knt mn m3a fransa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step
['is of the the']
['wach wakha 3la dima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
['you you to you']
['ghadi 3ndna nhar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
['to the the']
['mazal ghadi f7ali']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
['is to the']
['bzaf awlla had f ndiro ja l 3ndo o m3a8 3ndi dakchi maghadich nichan mzyan bzaf dyali']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
['you you this the you the the a and to the and you mean of to the']
['wach 3lih wach dyali 8owwa l liya o tmchi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
['you you you you a the me and to']
['ach wach wakha lli daba hya wa7d mnin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
['you you you you now the the you']
['men wakha m3a 7ta ttbib dyal sway3 miladi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
['i the a and of the and']
['nta o tjib ghda']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
['you you the the']
['dyal nafs fl 8owwa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
['of the the the']
['wahd nta o hada']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
['is you you to']
['7ta bghiti 3lach l wakha 3andak ch7al ola']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
['is to you the be the time you']
['knt bzzaf o sghar kan nakhad']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
['is good and your and and']
['l wahd nta o hada f homa mnin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
['the the of and a the the the']
['kayn bach 3lach kat3ref']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
['a to you you']
['wach wakha chwiya lma bghit kayb9aw ach bach l3adad fih dima wach khdit']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
['you you a of to later you you a of and you the']
['mer7ba tkon']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
['to']
['wach khra 7aja makaynach']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
['you you to a']
['b mabghitch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
['is to']
['kayn 3ndk ssogan kansma3 lmabadi2']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
['a you is very for']
['wach hahia l8na ri7la daraja nabid 3awntini']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
['you you here the a of in']
['ga3 dyal achmn']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
['of you']
['m3ettel fih 3tini lik rah zwin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
['is to to you you a']
['3chrin l7aja']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
['you']
['wach mezian 7aja imkan']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step
['you you to you']
['3aadatan dyal tilifoni']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
['good of and']
['nta o nokta had lia']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
['you you have this to']
['mli wach lli wach 3la dyal ghanmchi tlata']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
['you you you you to your time of']
['zwina kayn dyalk la dial']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
['is a you the']
['bzaf ana dwa haja kas']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
['you not very to work']
['dial bzaf mohim 8na achkhas 3lach dyal a tkon']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
['is of you here the you of you be']
['8ad bach 7ta chti7 jtima3 lia lmochkil lik ghadi zwin kif']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
['is to to a year and the you be the you']
['b7alek kantmana ghir']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
['you you be']
['imkan wach dyali 3ndo o lik sghira wach khra dyalk hada f zwin walakin dakchi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
['you a a and you you you you you to the the and you']
['knt 3afak o b chno']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
['is please you the you']
['daba ta9dar f allah']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
['you you the your']
['walakin machi l7afla dyalo ila ghadi ddar ddwa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
['not a to you to a a']
['o 9derna chi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
['me the']
['3ndhom m3a joj']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
['is to of']
['ostad chi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step
['a this']
['bnisba tche88it makanchoufch nta ala daraja maghadich ikon']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
['to of and you a to to']
['3afak o 3la katban']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
['you you the a']
['atay ghadi a8daf hadchi ljanobia']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
['of to to this you']
['ghadi lojik 3ndk wach achnahowa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
['to to the you you']
['3ndo had fiyya']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
['is this this']
['ykon daba haja 2oroppa machi nta nnhar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
['to now you the a to the']
['hna o lik kan hoa diali']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
['to the you you you to']
['wach 3la ssber walakin rah likan']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
['you you sick and is']
['m3a 3la f fnfs']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
['the the the the']
['imkan walo']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
['me']
['nta bli dyal kaml']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
['you you you of']
['3ndk rbat f l8emm momkin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
['you good in really and']
['mazal had tta']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step
['is this is']
['kifach mzyan bli sma7 bila ghadi lmohim ghadi 3ma']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
['you to you i be a to mean']
['bzaf ana kayna kidayr']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
['you not is to']
['li nta o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
['you you you']
['had b7al']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
['is is']
['kifach m3a dyali bl 3endi dyal kidazt machi wach dayz khddam knt wach lb7er walakin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
['you the your of the the the and you you to the you a you']
['dyalk ch7al n8ar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
['you you you']
['bach dyalk ghadi n8ar rrajl yallah bli nta tji nacht']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
['you you to the you you you you you to']
['lia ana riyada']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
['you not good']
['dyali wach joj chi 3lach']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
['is you of a you']
['bzaf nmchiw 3ndo had lma']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
['you to a this of']
['t li frasi ana lia']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
['the you you not be']
['chi skhouna tri9']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
['a is and']
['kaynin m3aya chi longli wach 3la ghadi kif walakin fayt ktab']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
['is me the the you to be you you you a']
['o l7lib hwa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
['is a']
['li kandir mn o 8owwa dakchi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
['you you the and a that']
['wach btata makaybanch la fach']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step
['you very bored and the']
['bach dyalk aji 8adi rah anna wach 7ayawan kandn google']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
['you you to the a a you to the your']

KeyboardInterrupt:

In [34]:
model.save("vanila_rnn_model.keras")

In [36]:
model2=models.Sequential()
model2.add(layers.Embedding(input_dim=len(tk_darja.word_index)+1,output_dim=64,input_length=32))
model2.add(layers.LSTM(64,return_sequences=True))
model2.add(layers.TimeDistributed(layers.Dense(len(tk_english.word_index)+1, activation="softmax")))

/home/yacine10/.local/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [37]:
model2.compile(optimizer="adam",loss="sparse_categorical_crossentropy")

In [39]:
model2.fit(x_train,y_train,epochs=10)

Epoch 1/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 100s 396ms/step - loss: 1.7791
Epoch 2/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 96s 382ms/step - loss: 1.3855
Epoch 3/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 95s 376ms/step - loss: 1.3609
Epoch 4/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 96s 379ms/step - loss: 1.3478
Epoch 5/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 95s 376ms/step - loss: 1.3368
Epoch 6/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 97s 383ms/step - loss: 1.3267
Epoch 7/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 95s 376ms/step - loss: 1.3177
Epoch 8/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 95s 375ms/step - loss: 1.3095
Epoch 9/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 96s 381ms/step - loss: 1.3013
Epoch 10/10
252/252 ━━━━━━━━━━━━━━━━━━━━ 96s 379ms/step - loss: 1.2902

In [ ]:
'''
for text in y_test:
    print(tk_darja.sequences_to_texts([text]))
    id=np.argmax(model2.predict(np.expand_dims(text,axis=0)),axis=-1)
    print(tk_english.sequences_to_texts(id))'''

['o imken 3ndi b3d 7da la dyal mra i9dr khayb chno']
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 977ms/step
['the the the the the the the the the']
['wach sma7 achno lel 7aja imkan lia 3tini']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
['of the the the the']
['bghiti f jib kay3jebni']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
['the the the']
['dyal kif hia achno msta3dda']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 282ms/step
['the the the']
['9bal mzyan bli nta lwa9t kolchi 3ndi lla deghya']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
['the the the the the the the of']
['mn o homa chrab kayna dakchi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
['the the the the the']
['wach b tkon salam ghadi 3tini']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
['the the the the']
['kayn wach knti o ma3ndich chi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
['you the the the']
['l wach 7ta rachid rah rasi f dyal iwa walakin machrob']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
['you the of of the the the the the']
['wach mazal dyal lflous b7al kandir']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
['the the the the']
['taniya ana kaddir ddirha ach 7aja makhasnach']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
['the the the the the the']
['bach 7aja imkan hna o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
['the the the the']
['makayl3bouch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
['']
['chi ana a9al nkhlik 9bel aykhasna dyal tma ya9dar l lla makan7malch f joz2']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
['the of the the the the the the the the the the the']
['bach ikono']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
['the']
['wach fl 3ndak fach lik aflam']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
['the the the of']
['ah ghadi wj8ou']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
['of']
['lia l7mar nmchiw laho3lem f llekher']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
['a the the the of']
['wach 3la f dialk mnin yallah dyal khasni taba9 tta9a walakin 3ndk zine']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
['you the of the the the the the the the the the']
['bzaf 8na goul walakin ghadi charika khod']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
['the the the the the the']
['wach bzzaf b l lksida kandn lik o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
['a the the the the the the']
['jaya dyali o simana machi nb9aw']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
['the the the the the']
['bghiti mabghitch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
['the']
['o l wach nta hada f dyal 2amrika']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
['the you the the the the of']
['bghitini dyali wach 3ndak o ghadi bllati momkin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
['the the the the the']
['wach ila lia ahya']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
['the']
['ta7ed wach wakha lkhdma n3awnak f ssout had']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
['the the the the of the']
['ana chno ghadi 7ad machi ana matalan sme3ti']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
['the the the the of']
['chi bjoj dima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
['the the']
['mzyan wach 3la dima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
['the the']
['3afak dyal tma khssni f homa walakin dyal yoga']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
['the the the the the the the of']
['8ad daba wa7ed machi dayer hamdolah nta 7aja onti walakin dyal blmonasaba']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step
['the the the of the the the the the']
['kayn wach 7ta l7ala f 3ndak ah tlflous mn o 3la']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step
['the the the the the of the the the']
['mzyan kbir o ma3ndich nchof fayt mbrre3']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
['the the the the the of']
['wach lkhdma f b tta']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
['the the the']
['dyalo ila f kat3awd lia lik mandir']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
['the the the the the']
['ch7al dakchi m3a nta la dyal lmajmo3a hadchi dyal fa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
['the the the the of the the']
['ykon o chokran ila machi nnas chamal annaho']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
['the the the the the of']
['makhddamach 3lach o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
['a the the']
['bzaf ana 7san']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
['the the']
['rah wa ana dyalk 7san']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
['the of the']
['daba fabor']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step
['the']
['o nta walakin kan ghlid annani']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
['the the the']
['sghira ay']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
['the']
['daba dyalk dyal kaml achmn']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step
['the the the the']
['zwina ga3 tal']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step
['the the']
['bach khasna b bghiti rah l3a2ila mawdo3 ba3d']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step
['the the the the the of of']
['dyali o 7ta dialk zwin la zwin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
['the of the the the']
['wakha dik hadi dyal n9tar7']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
['the the the']
['wa7d 7it mn machi l ayeh wach lkhdma f awal dyal hmm l7al hia 7ta 8owwa walakin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
['the the the the the the the the the the of of the the the the']
['8ad ach dyal mankonch 8na ghanmchi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
['a the the the']
['wach tbghi tkon hadi rah l7ayawanat']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
['a the the the of']
['daba dyalk ghadi kanchof 3lik bsa7 lkhadma nnas']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
['the the the the the the the']
['3lik tlwe9t chno lik kat9sad nit']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step
['you you you the the']
['ta7t o n3ref chofo']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step
['the the the']
['oh tmchi oh m3a bghiti tkon hadchi dyal a kbira b khddam mojito 14 3odw']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
['the the the the the the of the the of of of']
['dyali o bghiti ghadi ntla3 bnsba 3lach kan howwa f 3arf tkon wahd m3a nta']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step
['the the the the the the the the the the the the the the']
['3lik meziana achno lbal bghit makannakolch jani']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step
['a you the the of of']
['wach fin f 3ndi ghadi 3titini']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
['the the the the']
['ana lia bghit zwin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
['the the']
['daba ghadi fiha nglso ach 3lik mazyan achno rak ghir la rah fga3 n8ark']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
['the the of the the the the the the the the the']
['walakin ttani chi ssba7 had ghadi ndir hadchi fr7an bghit lmanga l l2a3mal']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step
['is the the the the the the the the of the the']
['wach ki machi 7it makltek 3lach dima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step
['the the the the the']
['dyal 7tta ana 7ta ism']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
['the the the the']
['kayn gal']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
['the']
['bach lmada9 f ngollik']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
['the the the']
['haja charab trf f 3ndi tl9na']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
['the the the the of']
['chwia o 8owwa khayb f hoa had ma3raftch chi bezzaf']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
['the the the the the the the the the']
['dyalo ndiro 8ad']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
['you the']
['dyalk machi chi ana rah ljow']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
['the the the the']
['machi ana dyal compte no9ta']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
['the of of']
['8ad daba ntchawfou']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
['you']
['ach la dyal kaml dima lw9t mabghitch kayna dyal charge mlli lmos3ifin daba ssimana']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
['the the the the the the the the the the the the']
['dyal flghalib bihom ana 3']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step
['the the the of']
['ban bach hadi o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step
['you the the']
['mti7an mti7an']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
['of']
['m3a lkhdma matreddedch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
['the the']
['o chwiya hakkak imkan men']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
['a the the the']
['mobtadi2 wach wakha 9adr lia dyalha la dial']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
['the the the the the the']
['m3a chwia b l kay3ejbek hadi dyal lmout l liya ah lmakla dyali khas']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
['the the the the the the the the the the the of of']
['bzaf bila 8ada']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
['the the']
['hoa had']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
['the']
['8adchi li 8na kan nhar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
['the the the']
['8adchi li 3afak o mn hadi kan tchouf 3ndek ymken']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
['the the the the the the the the']
['o nta dyalk ghadi frran']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
['the the of']
['m3a t9riban la bghitek']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
['of the']
['wach lli tari9a khososan nta 7aja ghir dak']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
['the the the the the the']
['wach 7na lou9id']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
['the']
['bzaf ana i9dar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
['the the']
['lmakla 8na tsenna 3lach dyal nhar hadchi dyal fchi l ch7al m3a fhmtini f annak ikon me9li oh walakin dyal galiyya']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
['the of the the the the the the the the the of the the of the the the the']
['wahd nta o kayna walakin dyal maghadi msafer']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
['you the the the the the of']
['bach ttarikh']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
['the']
['wla ghadi l3chiya l7am o']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
['the of the']
['kaynin wach chwiya daba aji']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
['a the the the']
['khayba 3lach dyal takol']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
['the the the']
['ana chno restora tbeddel walakin dyal a7san']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
['the the the the the']
['chi lil b7al']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
['the the']
['wakha o 3la ghadi lkelb f bghiti ghadi miladek kayna ghadi mkhlou3']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
['the the the the the the of the the the']
['khayba wa7d']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
['the']
['8ad hadchi t9der']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
['']
['bzaf tani f n9der ah banjo ana']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step
['the the the the the the']
['wach sma7 tl o 3ziz']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
['the the the']
['bghit wajda t3llmti']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
['the of the']
['wach lb7er walakin maghadich imta howa f matb9ach dyal f7alna']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
['a the the the the the of the the']
['wach ila anna lik chkoun khoya l motir']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
['the you the of the the']
['lik rah zwin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
['the']
['chi ana kan ktabi lihom dial']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
['the the the the the']
['wach 3la ghadi tji mti99en makan3rafch ga3 dial']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
['the the the of the the']
['dyal takol ana annana f rriyada']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
['the the the the of']
['wach lkhdma maths rah kima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
['of the the']
['s7i7 we9t jiti rah lkhrin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
['is the the the of']
['kayn ga3 choklat']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
['the of']
['wach l7lib drhem dyal n9dar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
['a of the']
['nta o ghadi ghir mezian']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
['the the the']
['momkin mzyana dyalk']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
['the of']
['nta o kindir bezzaf dyal ssrf hadi kan howwa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
['the the the of the the the']
['mn o b9at makentich']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
['the the of']
['mli machi kolchi ndiro 3liyya']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step
['the the the']
['wach 3lih o chwiya li f mn machi 3lach kan b3id']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
['the the the the the the the the of']
['daba makan7malch 8adi mskin s3ib']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
['the the the the']
['wla dyalk ala walakin ghadi tri9 maddirch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
['a the the the the the']
['ah bghit 8iyya ghadi chriti']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
['the the the the']
['mzyan o kter walakin dakchi m3a chwia homa ahlan']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
['the of the the the the the of']
['lktab ana kon']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step
['the the']
['wakha mn machi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step
['a the']
['lmakla hia mazyan achno mrida']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
['the the the of']
['wach fl chwiya li f 3ndo o ach wach lli wach jjame3 chi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step
['the the the the the the you the the of the']
['wla yjiw dar fach']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step
['a the the']
['knt mn m3a fransa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
['the the the']
['wach wakha 3la dima']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
['the the']
['ghadi 3ndna nhar']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step
['the the']
['mazal ghadi f7ali']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step
['the the']
['bzaf awlla had f ndiro ja l 3ndo o m3a8 3ndi dakchi maghadich nichan mzyan bzaf dyali']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
['the the the the the the the the the the the the of the of of']
['wach 3lih wach dyali 8owwa l liya o tmchi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step
['you the the the the the the']
['ach wach wakha lli daba hya wa7d mnin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
['a the the the the the']
['men wakha m3a 7ta ttbib dyal sway3 miladi']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
['the the the the the the']
['nta o tjib ghda']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
['you the']
['dyal nafs fl 8owwa']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
['the the the']
['wahd nta o hada']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
['you the the']
['7ta bghiti 3lach l wakha 3andak ch7al ola']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
['the the the the the the the']
['knt bzzaf o sghar kan nakhad']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
['the the of the the']
['l wahd nta o hada f homa mnin']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step
['the the the the the the the']
['kayn bach 3lach kat3ref']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
['the the the']
['wach wakha chwiya lma bghit kayb9aw ach bach l3adad fih dima wach khdit']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
['the the the of the of the the the the']
['mer7ba tkon']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
['you']
['wach khra 7aja makaynach']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
['a the the']
['b mabghitch']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step
['the']
['kayn 3ndk ssogan kansma3 lmabadi2']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
['the the the the']
['wach hahia l8na ri7la daraja nabid 3awntini']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
['the the the the the']
['ga3 dyal achmn']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
['the the']
['m3ettel fih 3tini lik rah zwin']

KeyboardInterrupt: